# Request Library in Python for Web Craping

In [ ]:
import requests

In [ ]:
url = "https://courses.wscubetech.com/courses/web-scraping-python-course-638dc4ade4b0234e2c992668"
r = requests.get(url)

In [ ]:
print(r.status_code)
print(r.text)

401
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty</center>
</body>
</html>

# How to Parse HTML Content using BeautifulSoup

In [ ]:
from bs4 import BeautifulSoup
import requests

In [ ]:
url = "https://webscraper.io/test-sites/e-commerce/allinone/computers"
r = requests.get(url)


soup = BeautifulSoup(r.text, "lxml")

print(r.status_code)
print(soup.body.h1)
print(soup.body.h2)
print(soup.body.h3)

200
<h1>Test Sites</h1>
<h2 class="page-header">Computers category</h2>
<h3>Top items being scraped right now</h3>

# Attribute in HTML

In [ ]:
url = "https://webscraper.io/test-sites/e-commerce/allinone/computers"
r = requests.get(url)


soup = BeautifulSoup(r.text, 'lxml')
tag = soup.header


print(tag.attrs)

{'role': 'banner', 'class': ['navbar', 'fixed-top', 'navbar-expand-lg', 'navbar-dark', 'navbar-static', 'svg-background'], 'id': 'navbar-top'}

In [ ]:
paragraphs = soup.find_all("p")
for p in paragraphs:
    print(p.text)

Web Scraper
Cloud Scraper
Pricing

								Learn


Asus VivoBook 15 X540NA-GQ026T Chocolate Black, 15.6" HD, Pentium N4200, 4GB, 128GB SSD, Windows 10 Home, En/Ru kbd
4 reviews






Dell Latitude 5280, 12.5" HD, Core i5-7300U, 8GB, 256GB SSD, Windows 10 Pro
8 reviews



15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1
2 reviews




Products
Company
Resources
CONTACT US
Copyright &copy 2025
					Web Scraper | All rights reserved

# Navigable Strings in Html Tutorial for Beginners

In [ ]:
url = "https://webscraper.io/test-sites/e-commerce/allinone/computers"
r = requests.get(url)


soup = BeautifulSoup(r.text, 'lxml')
tag = soup.div.p


print(tag.string)

Web Scraper

# How BeautifulSoup - find() Function Work ?

In [ ]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets'
r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

print(soup.find('div'))

<div class="container">
<div class="navbar-header">
<a data-bs-target=".side-collapse" data-bs-target-2=".side-collapse-container" data-bs-toggle="collapse-side">
<button aria-controls="navbar" aria-expanded="false" class="navbar-toggler float-end collapsed" data-bs-target="#navbar" data-bs-target-2=".side-collapse-container" data-bs-target-3=".side-collapse" data-bs-toggle="collapse" type="button">
<span class="visually-hidden">Toggle navigation</span>
<span class="icon-bar top-bar"></span>
<span class="icon-bar middle-bar"></span>
<span class="icon-bar bottom-bar"></span>
<span class="icon-bar extra-bottom-bar"></span>
</button>
</a>
<div class="navbar-brand">
<a href="/"><img alt="Web Scraper" src="/img/logo_white.svg"/></a>
</div>
</div>
<div class="side-collapse in">
<nav class="navbar-collapse collapse" id="navbar" role="navigation">
<ul class="nav navbar-nav navbar-right">
<li class="nav-item">
<a class="nav-link menuitm" href="/">
<p>Web Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/cloud-scraper" id="cloud-nav-link">
<p>Cloud Scraper</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item">
<a class="nav-link menuitm" href="/pricing" id="pricing-nav-link">
<p>Pricing</p>
<div class="crta"></div>
</a>
</li>
<li class="nav-item dropdown">
<button aria-expanded="false" aria-haspopup="true" class="menuitm nav-link dropdown-toggle" data-bs-toggle="dropdown" id="dropdownMenuLink" role="button">
<p>
								Learn
								<i class="ws-icon ws-icon-down"></i>
</p>
<span class="crta"></span>
</button>
<ul aria-labelledby="dropdownMenuLink" class="dropdown-menu">
<li>
<a class="dropdown-item" href="/documentation">Documentation</a>
</li>
<li>
<a class="dropdown-item" href="/tutorials">Video Tutorials</a>
</li>
<li>
<a class="dropdown-item" href="/test-sites">Test Sites</a>
</li>
<li>
<a class="dropdown-item" href="https://forum.webscraper.io/" rel="noopener" target="_blank">Forum</a>
</li>
</ul>
</li>
<li class="nav-item">
<a class="nav-link btn-menu1 install-extension" href="https://chromewebstore.google.com/detail/web-scraper-free-web-scra/jnhgnonknehpejjnehehllkliplmbmhn?hl=en" target="_blank">Install</a>
</li>
<li class="nav-item">
<a class="nav-link btn-menu2" href="https://cloud.webscraper.io/">Cloud Login</a>
</li>
</ul>
</nav>
</div>
</div>

In [ ]:
price = (soup.find("h4", {"class":"price float-end card-title pull-right"}))
print(price.string)

title = soup.find("a", {"class" : "title"})
print(title.string)

description = soup.find("p", {"class" : "description card-text"})
print(description.string)


## another way

title = soup.find("a", class_ = "title")
print(title.string)

$69.99
Lenovo IdeaTab
7" screen, Android
Lenovo IdeaTab

# BeutifulSoup - find_all() function with tags and attributes

In [ ]:
title = soup.find_all("a", class_ = "title")
for p in title:
  print(p.text)

price = soup.find_all("h4", class_ = 'price float-end card-title pull-right')
for p in price:
  print(p.string)
des = soup.find_all("p", class_ = 'description card-text')
for d in des:
  print(d.text)

Lenovo IdeaTab
IdeaTab A3500L
Acer Iconia
Galaxy Tab 3
Iconia B1-730H...
Memo Pad HD 7
Asus MeMO Pad
Amazon Kindle
Galaxy Tab 3
IdeaTab A8-50
MeMO Pad 7
IdeaTab A3500-...
IdeaTab S5000
Galaxy Tab 4
Galaxy Tab
MeMo PAD FHD 1...
Galaxy Note
Galaxy Note
iPad Mini Reti...
Galaxy Note 10...
Apple iPad Air
$69.99
$88.99
$96.99
$97.99
$99.99
$101.99
$102.99
$103.99
$107.99
$121.99
$130.99
$148.99
$172.99
$233.99
$251.99
$320.99
$399.99
$489.99
$537.99
$587.99
$603.99
7" screen, Android
Black, 7" IPS, Quad-Core 1.2GHz, 8GB, Android 4.2
7" screen, Android, 16GB
7", 8GB, Wi-Fi, Android 4.2, White
Black, 7", 1.6GHz Dual-Core, 8GB, Android 4.4
IPS, Dual-Core 1.2GHz, 8GB, Android 4.3
7" screen, Android, 8GB
6" screen, wifi
7", 8GB, Wi-Fi, Android 4.2, Yellow
Blue, 8" IPS, Quad-Core 1.3GHz, 16GB, Android 4.2
White, 7", Atom 1.2GHz, 8GB, Android 4.4
Blue, 7" IPS, Quad-Core 1.3GHz, 8GB, 3G, Android 4.2
Silver, 7" IPS, Quad-Core 1.2Ghz, 16GB, 3G, Android 4.2
LTE (SM-T235), Quad-Core 1.2GHz, 8GB, Black
16GB, White
White, 10.1" IPS, 1.6GHz, 2GB, 16GB, Android 4.2
10.1", 3G, Android 4.0, Garnet Red
12.2", 32GB, WiFi, Android 4.4, White
Wi-Fi + Cellular, 32GB, Silver
10.1", 32GB, Black
Wi-Fi, 64GB, Silver

In [ ]:
for p, t, d in zip(price, title, des):
  print(p.string, t.string, d.text)

$69.99 Lenovo IdeaTab 7" screen, Android
$88.99 IdeaTab A3500L Black, 7" IPS, Quad-Core 1.2GHz, 8GB, Android 4.2
$96.99 Acer Iconia 7" screen, Android, 16GB
$97.99 Galaxy Tab 3 7", 8GB, Wi-Fi, Android 4.2, White
$99.99 Iconia B1-730H... Black, 7", 1.6GHz Dual-Core, 8GB, Android 4.4
$101.99 Memo Pad HD 7 IPS, Dual-Core 1.2GHz, 8GB, Android 4.3
$102.99 Asus MeMO Pad 7" screen, Android, 8GB
$103.99 Amazon Kindle 6" screen, wifi
$107.99 Galaxy Tab 3 7", 8GB, Wi-Fi, Android 4.2, Yellow
$121.99 IdeaTab A8-50 Blue, 8" IPS, Quad-Core 1.3GHz, 16GB, Android 4.2
$130.99 MeMO Pad 7 White, 7", Atom 1.2GHz, 8GB, Android 4.4
$148.99 IdeaTab A3500-... Blue, 7" IPS, Quad-Core 1.3GHz, 8GB, 3G, Android 4.2
$172.99 IdeaTab S5000 Silver, 7" IPS, Quad-Core 1.2Ghz, 16GB, 3G, Android 4.2
$233.99 Galaxy Tab 4 LTE (SM-T235), Quad-Core 1.2GHz, 8GB, Black
$251.99 Galaxy Tab 16GB, White
$320.99 MeMo PAD FHD 1... White, 10.1" IPS, 1.6GHz, 2GB, 16GB, Android 4.2
$399.99 Galaxy Note 10.1", 3G, Android 4.0, Garnet Red
$489.99 Galaxy Note 12.2", 32GB, WiFi, Android 4.4, White
$537.99 iPad Mini Reti... Wi-Fi + Cellular, 32GB, Silver
$587.99 Galaxy Note 10... 10.1", 32GB, Black
$603.99 Apple iPad Air Wi-Fi, 64GB, Silver

# Beautiful Soup find_all() methods

In [ ]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets'
r = requests.get(url)

soup = BeautifulSoup(r.text, "lxml")
r.status_code

200

In [ ]:
X = soup.find_all(['a', 'p', 'h1'], class_ = ["title", "description", "price float-end card-title pull-right"])
for i in X:
  print(i.text, ' ')

Lenovo IdeaTab
7" screen, Android
IdeaTab A3500L
Black, 7" IPS, Quad-Core 1.2GHz, 8GB, Android 4.2
Acer Iconia
7" screen, Android, 16GB
Galaxy Tab 3
7", 8GB, Wi-Fi, Android 4.2, White
Iconia B1-730H...
Black, 7", 1.6GHz Dual-Core, 8GB, Android 4.4
Memo Pad HD 7
IPS, Dual-Core 1.2GHz, 8GB, Android 4.3
Asus MeMO Pad
7" screen, Android, 8GB
Amazon Kindle
6" screen, wifi
Galaxy Tab 3
7", 8GB, Wi-Fi, Android 4.2, Yellow
IdeaTab A8-50
Blue, 8" IPS, Quad-Core 1.3GHz, 16GB, Android 4.2
MeMO Pad 7
White, 7", Atom 1.2GHz, 8GB, Android 4.4
IdeaTab A3500-...
Blue, 7" IPS, Quad-Core 1.3GHz, 8GB, 3G, Android 4.2
IdeaTab S5000
Silver, 7" IPS, Quad-Core 1.2Ghz, 16GB, 3G, Android 4.2
Galaxy Tab 4
LTE (SM-T235), Quad-Core 1.2GHz, 8GB, Black
Galaxy Tab
16GB, White
MeMo PAD FHD 1...
White, 10.1" IPS, 1.6GHz, 2GB, 16GB, Android 4.2
Galaxy Note
10.1", 3G, Android 4.0, Garnet Red
Galaxy Note
12.2", 32GB, WiFi, Android 4.4, White
iPad Mini Reti...
Wi-Fi + Cellular, 32GB, Silver
Galaxy Note 10...
10.1", 32GB, Black
Apple iPad Air
Wi-Fi, 64GB, Silver

In [ ]:
Y = soup.find_all(string = "Galaxy Tab 4")
print(Y)


import re

data = soup.find_all(string = re.compile("Galaxy"))
print(len(data))

['Galaxy Tab 4']
7

# Web Scraping with BeautifulSoup and Pandas

In [ ]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets"
r = requests.get(url)

soup = BeautifulSoup(r.text, 'lxml')

In [ ]:
name = soup.find_all('a', class_ = 'title')

for n in range(len(name)):
  name[n] = name[n].string

price = soup.find_all("h4", class_ = 'price float-end card-title pull-right')

for p in range(len(price)):
  price[p] = price[p].text


des = soup.find_all("p", class_ = 'description card-text')
for d in range(len(des)):
  des[d] = des[d].string

reviews = soup.find_all('p', class_ = "review-count float-end")
for r in range(len(reviews)):
  reviews[r] = reviews[r].text

In [ ]:
data = pd.DataFrame()

data['Prodeuct Name']  = name
data['Price'] = price
data['Description'] = des
data['Reviews Count'] = reviews


data.to_csv("Products_details.csv")

# Extract Data from Nested HTML Tags - Explained

- Sử dụng re.compile("Galaxy") để tìm các phần tử có chứa chuỗi "Galaxy" trong nội dung text.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas

In [ ]:
url = 'https://webscraper.io/test-sites/e-commerce/allinone/computers/tablets'
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
proxies = {
    "http": "http://your-proxy.com",
    "https": "https://your-proxy.com"
}
r = requests.get(url, headers = headers)

In [ ]:
r.status_code

200

In [ ]:
soup = BeautifulSoup(r.text, 'lxml')


boxes = soup.find_all("div", class_ = "col-md-4 col-xl-4 col-lg-4")[2]


name = boxes.find("a")
print(name.string)


des = boxes.find('p', class_ = 'description')
print(des.text)

price = boxes.find('h4', class_ = "price float-end card-title pull-right")
print(price.string)

Acer Iconia
7" screen, Android, 16GB
$96.99

# How to Scrape a Table From a Website using BeautifulSoup

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
#url = 'https://www.oneindia.com/coronavirus-affected-cities-districts-in-india.html?utm_medium=Oneindia&utm_source=OI-EN&utm_campaign=Corona-Spl-Pages'


url = 'https://ticker.finology.in/market/52-week-high'
r = requests.get(url)
print(r)

<Response [200]>

In [ ]:
soup = BeautifulSoup(r.text, 'lxml')
file = soup.find_all('tbody')[0]

In [ ]:
feature = file.find_all('tr')


for i in range(len(feature)):
  feature[i] = feature[i].text
print(feature[0])

1
A-1
458.35
534.80

In [ ]:
data = pd.DataFrame()
data['Index'] = {}
data['Company_Name'] = {}
data['Price'] = {}
data['Day High'] = {}

data

Empty DataFrame
Columns: [Index, Company_Name, Price, Day High]
Index: []

In [ ]:
for i in range(len(feature)):
  lines = feature[i].split("\n")  # Tách theo dòng
  index = lines[1]  # "1"
  company_name = lines[2]  # "Bajaj Finance"
  price_1 = float(lines[3])  # 8731.60
  price_2 = float(lines[4])  # 8879.00
  data.loc[len(data)] = [index, company_name, price_1, price_2]

In [ ]:
data

   Index          Company_Name    Price  Day High
0      1                   A-1   458.35    534.80
1      2          Welspun Corp   871.55    889.00
2      3   Narayana Hrudayalay  1684.80   1719.90
3      4   Interglobe Aviation  5093.05   5187.00
4      5      Aavas Financiers  1978.85   1997.00
..   ...                   ...      ...       ...
57    58    Bhudevi Infra Proj   197.55    197.55
58    59  Yash Trading&Finance    92.66     92.66
59    60        Vega Jewellers    35.19     35.19
60    61  HEM Holdings&Trading    15.85     15.85
61    62    Omansh Enterprises    11.48     11.48

[62 rows x 4 columns]

In [ ]:
data.to_csv('data')

# How to Scrape a Table From a Website using BeautifulSoup

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
url = "https://ticker.finology.in/"
r = requests.get(url)

In [ ]:
print(r.status_code)

200

In [ ]:
soup = BeautifulSoup(r.content, 'html.parser')

In [ ]:
table = soup.find_all('table', class_="table table-sm table-hover screenertable")[0]

In [ ]:

titles = []
headers = table.find_all("th")
for h in headers:
  print(h.text)
  titles.append(h.text)

Company
PriceRs.
Day HighRs.

In [ ]:
data_df = pd.DataFrame(columns= titles)
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      0 non-null      object
 1   PriceRs.     0 non-null      object
 2   Day HighRs.  0 non-null      object
dtypes: object(3)
memory usage: 132.0+ bytes

In [ ]:
data = table.find('tbody')
rows = data.find_all('tr')
for r in rows:
  name = r.find_all('td')[0].text
  name = name.replace('\n', '').strip()
  price = r.find_all('td')[1].text
  high_price = r.find_all('td')[2].text
  data_df.loc[len(data_df)] = [name, price, high_price]

In [ ]:
data_df

                Company  PriceRs. Day HighRs.
0    Manappuram Finance    234.25      247.55
1         Bajaj Finance   8918.60     9070.00
2            ITC Hotels    198.50      204.45
3   Kotak Mahindra Bank   2084.40     2096.00
4          JSW Holdings  22975.05    23150.00
5                   SRF   3018.20     3050.00
6         CarTrade Tech   1812.65     1885.00
7   Ventive Hospitality    790.00      810.40
8                   UPL    663.15      671.00
9   Blue Jet Healthcare    906.00      968.75
10  Chambal Fert & Chem    596.00      598.45
11         Welspun Corp    879.55      892.25
12         Shree Cement  28930.65    29300.00
13      Axiscades Tech.    965.05      965.05
14      Colab Platforms     85.95       85.95

# How to Scrap Data from TATA IPL Auction?

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
url = "https://www.iplt20.com/auction"
r = requests.get(url)
print(r.status_code)

200

In [ ]:
soup = BeautifulSoup(r.text, "lxml")

In [ ]:
table = soup.find_all("div", class_ = "auction-grid-view mt-3")

In [ ]:
temp = soup.find_all('div', class_ = "ih-points-table-sec aulistview", style_ = "display: block;")

In [ ]:
print(len(temp))

0

- Khong th caof trnag web nay boi no cai dat bang javascripts

# How to Scrape Multiple Pages on Websites

In [ ]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
url = "https://books.toscrape.com/catalogue/page-1.html"

In [ ]:
r = requests.get(url)
print(r.status_code)

200

In [ ]:
soup = BeautifulSoup(r.content, 'html.parser')

# Lấy danh sách tất cả các tên sách

In [ ]:
ol = soup.find_all('ol', class_ = "row")
print(len(ol))

1

In [ ]:
li = ol[0].find_all('li', class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [ ]:
print(len(li))

20

In [ ]:
artical = ol[0].find_all('article', class_ = "product_pod")

In [ ]:
for a in artical:
  a_ = a.find('h3')
  b = a_.find('a')
  print(b.attrs['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [ ]:
for a in li:
  a_ = a.find('h3')
  b = a_.find('a')
  print(b.attrs['title'])
  star = a.find('p')
  star = star['class'][1]
  print(star)
  price = a.find('p', class_ = "price_color")
  print(price.text)

A Light in the Attic
Three
£51.77
Tipping the Velvet
One
£53.74
Soumission
One
£50.10
Sharp Objects
Four
£47.82
Sapiens: A Brief History of Humankind
Five
£54.23
The Requiem Red
One
£22.65
The Dirty Little Secrets of Getting Your Dream Job
Four
£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Three
£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Four
£22.60
The Black Maria
One
£52.15
Starving Hearts (Triangular Trade Trilogy, #1)
Two
£13.99
Shakespeare's Sonnets
Four
£20.66
Set Me Free
Five
£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Five
£52.29
Rip it Up and Start Again
Five
£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Three
£57.25
Olio
One
£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849
One
£37.59
Libertarianism for Beginners
Two
£51.33
It's Only the Himalayas
Two
£45.17

In [ ]:
# Other way, instead of using artical, i use ol
for a in artical:
  a_ = a.find('h3')
  b = a_.find('a')
  print(b.attrs['title'])
  star = a.find('p')
  star = star.attrs['class'][1]
  print(star)
  price = a.find('p', class_ = "price_color")
  print(price.text)

A Light in the Attic
Three
£51.77
Tipping the Velvet
One
£53.74
Soumission
One
£50.10
Sharp Objects
Four
£47.82
Sapiens: A Brief History of Humankind
Five
£54.23
The Requiem Red
One
£22.65
The Dirty Little Secrets of Getting Your Dream Job
Four
£33.34
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Three
£17.93
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Four
£22.60
The Black Maria
One
£52.15
Starving Hearts (Triangular Trade Trilogy, #1)
Two
£13.99
Shakespeare's Sonnets
Four
£20.66
Set Me Free
Five
£17.46
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Five
£52.29
Rip it Up and Start Again
Five
£35.02
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Three
£57.25
Olio
One
£23.88
Mesaerion: The Best Science Fiction Stories 1800-1849
One
£37.59
Libertarianism for Beginners
Two
£51.33
It's Only the Himalayas
Two
£45.17

## Phía trên ta mới chỉ đang tìm page 1. Nhưng trang web lại có tận 50 trang.
idea : Can thiệp vào url, chạy một vòng for vào url để sửa page{i}

In [ ]:
def printt(r):
  soup = BeautifulSoup(r.content, 'lxml')
  li = soup.find_all('li', class_ = "col-xs-6 col-sm-4 col-md-3 col-lg-3")
  for l in li:
    a = l.find('img')
    print(a.attrs['alt'])
    star = l.find('p')
    print(star.attrs['class'][1])

In [ ]:
for i in range(1, 51):
  url = f"https://books.toscrape.com/catalogue/page-{i}.html"
  r = requests.get(url)
  printt(r)

A Light in the Attic
Three
Tipping the Velvet
One
Soumission
One
Sharp Objects
Four
Sapiens: A Brief History of Humankind
Five
The Requiem Red
One
The Dirty Little Secrets of Getting Your Dream Job
Four
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
Three
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
Four
The Black Maria
One
Starving Hearts (Triangular Trade Trilogy, #1)
Two
Shakespeare's Sonnets
Four
Set Me Free
Five
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Five
Rip it Up and Start Again
Five
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Three
Olio
One
Mesaerion: The Best Science Fiction Stories 1800-1849
One
Libertarianism for Beginners
Two
It's Only the Himalayas
Two
In Her Wake
One
How Music Works
Two
Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More
Three
Chase Me (Paris Nights #2)
Five
Black Dust
Five
Birdsong: A Story in Pictures
Three
America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana
Three
Aladdin and His Wonderful Lamp
Three
Worlds Elsewhere: Journeys Around Shakespeare’s Globe
Five
Wall and Piece
Four
The Four Agreements: A Practical Guide to Personal Freedom
Five
The Five Love Languages: How to Express Heartfelt Commitment to Your Mate
Three
The Elephant Tree
Five
The Bear and the Piano
One
Sophie's World
Five
Penny Maybe
Three
Maude (1883-1993):She Grew Up with the country
Two
In a Dark, Dark Wood
One
Behind Closed Doors
Four
You can't bury them all: Poems
Two
Slow States of Collapse: Poems
Three
Reasons to Stay Alive
Two
Private Paris (Private #10)
Five
#HigherSelfie: Wake Up Your Life. Free Your Soul. Find Your Tribe.
Five
Without Borders (Wanderlove #1)
Two
When We Collided
One
We Love You, Charlie Freeman
Five
Untitled Collection: Sabbath Poems 2014
Four
Unseen City: The Majesty of Pigeons, the Discreet Charm of Snails & Other Wonders of the Urban Wilderness
Four
Unicorn Tracks
Three
Unbound: How Eight Technologies Made Us Human, Transformed Society, and Brought Our World to the Brink
One
Tsubasa: WoRLD CHRoNiCLE 2 (Tsubasa WoRLD CHRoNiCLE #2)
One
Throwing Rocks at the Google Bus: How Growth Became the Enemy of Prosperity
Three
This One Summer
Four
Thirst
Five
The Torch Is Passed: A Harding Family Story
One
The Secret of Dreadwillow Carse
One
The Pioneer Woman Cooks: Dinnertime: Comfort Classics, Freezer Food, 16-Minute Meals, and Other Delicious Ways to Solve Supper!
One
The Past Never Ends
Four
The Natural History of Us (The Fine Art of Pretending #2)
Three
The Nameless City (The Nameless City #1)
Four
The Murder That Never Was (Forensic Instincts #5)
Three
The Most Perfect Thing: Inside (and Outside) a Bird's Egg
Four
The Mindfulness and Acceptance Workbook for Anxiety: A Guide to Breaking Free from Anxiety, Phobias, and Worry Using Acceptance and Commitment Therapy
Four
The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing
Three
The Inefficiency Assassin: Time Management Tactics for Working Smarter, Not Longer
Five
The Gutsy Girl: Escapades for Your Life of Epic Adventure
One
The Electric Pencil: Drawings from Inside State Hospital No. 3
One
The Death of Humanity: and the Case for Life
Four
The Bulletproof Diet: Lose up to a Pound a Day, Reclaim Energy and Focus, Upgrade Your Life
Three
The Art Forger
Three
The Age of Genius: The Seventeenth Century and the Birth of the Modern Mind
One
The Activist's Tao Te Ching: Ancient Advice for a Modern Revolution
Five
Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up
Four
Soul Reader
Two
Security
Two
Saga, Volume 6 (Saga (Collected Editions) #6)
Three
Saga, Volume 5 (Saga (Collected Editions) #5)
Two
Reskilling America: Learning to Labor in the Twenty-First Century
Two
Rat Queens, Vol. 3: Demons (Rat Queens (Collected Editions) #11-15)
Three
Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)
Five
Princess Between Worlds (Wide-Awake Princess #5)
Five
Pop Gun War, Volume 1: Gift
One
Political Suicide: Missteps, Peccadilloes, Bad Calls, Backroom Hijinx, Sordid Pasts, Rotten Breaks, and Just Plain Dumb Mistakes in the Annals of American Politics
Two
Patience
Three
Outcast, Vol. 1: A Darkness Surrounds Him (Outcast #1)
Four
orange: The Complete Collection 1 (orange: The Complete Collection #1)
One
Online Marketing for Busy Authors: A Step-By-Step Guide
One
On a Midnight Clear
Three
Obsidian (Lux #1)
Two
My Paris Kitchen: Recipes and Stories
Two
Masks and Shadows
Two
Mama Tried: Traditional Italian Cooking for the Screwed, Crude, Vegan, and Tattooed
Four
Lumberjanes, Vol. 2: Friendship to the Max (Lumberjanes #5-8)
Two
Lumberjanes, Vol. 1: Beware the Kitten Holy (Lumberjanes #1-4)
Three
Lumberjanes Vol. 3: A Terrible Plan (Lumberjanes #9-12)
Two
Layered: Baking, Building, and Styling Spectacular Cakes
One
Judo: Seven Steps to Black Belt (an Introductory Guide for Beginners)
Two
Join
Five
In the Country We Love: My Family Divided
Four
Immunity: How Elie Metchnikoff Changed the Course of Modern Medicine
Five
I Hate Fairyland, Vol. 1: Madly Ever After (I Hate Fairyland (Compilations) #1-5)
Two
I am a Hero Omnibus Volume 1
Three
How to Be Miserable: 40 Strategies You Already Use
One
Her Backup Boyfriend (The Sorensen Family #1)
One
Giant Days, Vol. 2 (Giant Days #5-8)
Two
Forever and Forever: The Courtship of Henry Longfellow and Fanny Appleton
Three
First and First (Five Boroughs #3)
Four
Fifty Shades Darker (Fifty Shades #2)
One
Everydata: The Misinformation Hidden in the Little Data You Consume Every Day
Two
Don't Be a Jerk: And Other Practical Advice from Dogen, Japan's Greatest Zen Master
Two
Danganronpa Volume 1
Four
Crown of Midnight (Throne of Glass #2)
Three
Codename Baboushka, Volume 1: The Conclave of Death
Four
Camp Midnight
Four
Call the Nurse: True Stories of a Country Nurse on a Scottish Isle
Five
Burning
Three
Bossypants
Two
Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))
Two
Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)
Two
Algorithms to Live By: The Computer Science of Human Decisions
One
A World of Flavor: Your Gluten Free Passport
One
A Piece of Sky, a Grain of Rice: A Memoir in Four Meditations
Five
A Murder in Time
One
A Flight of Arrows (The Pathfinders #2)
Five
A Fierce and Subtle Poison
Four
A Court of Thorns and Roses (A Court of Thorns and Roses #1)
One
(Un)Qualified: How God Uses Broken People to Do Big Things
Five
You Are What You Love: The Spiritual Power of Habit
Four
William Shakespeare's Star Wars: Verily, A New Hope (William Shakespeare's Star Wars #4)
Four
Tuesday Nights in 1980
Two
Tracing Numbers on a Train
Three
Throne of Glass (Throne of Glass #1)
Three
Thomas Jefferson and the Tripoli Pirates: The Forgotten War That Changed American History
One
Thirteen Reasons Why
One
The White Cat and the Monk: A Retelling of the Poem “Pangur Bán”
Four
The Wedding Dress
One
The Vacationers
Four
The Third Wave: An Entrepreneur’s Vision of the Future
Five
The Stranger
Four
The Shadow Hero (The Shadow Hero)
One
The Secret (The Secret #1)
Four
The Regional Office Is Under Attack!
Five
The Psychopath Test: A Journey Through the Madness Industry
Two
The Project
One
The Power of Now: A Guide to Spiritual Enlightenment
Two
The Omnivore's Dilemma: A Natural History of Four Meals
Two
The Nerdy Nummies Cookbook: Sweet Treats for the Geek in All of Us
Five
The Murder of Roger Ackroyd (Hercule Poirot #4)
Four
The Mistake (Off-Campus #2)
Three
The Matchmaker's Playbook (Wingmen Inc. #1)
One
The Love and Lemons Cookbook: An Apple-to-Zucchini Celebration of Impromptu Cooking
Two
The Long Shadow of Small Ghosts: Murder and Memory in an American City
One
The Kite Runner
Four
The House by the Lake
One
The Glittering Court (The Glittering Court #1)
One
The Girl on the Train
Two
The Genius of Birds
One
The Emerald Mystery
Two
The Cookies & Cups Cookbook: 125+ sweet & savory recipes reminding you to Always Eat Dessert First
One
The Bridge to Consciousness: I'm Writing the Bridge Between Science and Our Old and New Beliefs.
Three
The Artist's Way: A Spiritual Path to Higher Creativity
Five
The Art of War
Five
The Argonauts
Two
The 10% Entrepreneur: Live Your Startup Dream Without Quitting Your Day Job
Three
Suddenly in Love (Lake Haven #1)
Two
Something More Than This
Four
Soft Apocalypse
Two
So You've Been Publicly Shamed
Two
Shoe Dog: A Memoir by the Creator of NIKE
Two
Shobu Samurai, Project Aryoku (#3)
Three
Secrets and Lace (Fatal Hearts #1)
One
Scarlett Epstein Hates It Here
Five
Romero and Juliet: A Tragic Tale of Love and Zombies
One
Redeeming Love
Five
Poses for Artists Volume 1 - Dynamic and Sitting Poses: An Essential Reference for Figure Drawing and the Human Form
One
Poems That Make Grown Women Cry
Four
Nightingale, Sing
One
Night Sky with Exit Wounds
One
Mrs. Houdini
Five
Modern Romance
Five
Miss Peregrine’s Home for Peculiar Children (Miss Peregrine’s Peculiar Children #1)
One
Louisa: The Extraordinary Life of Mrs. Adams
Two
Little Red
Three
Library of Souls (Miss Peregrine’s Peculiar Children #3)
Five
Large Print Heart of the Pride
Two
I Had a Nice Time And Other Lies...: How to find love & sh*t like that
Four
Hollow City (Miss Peregrine’s Peculiar Children #2)
One
Grumbles
Two
Full Moon over Noah’s Ark: An Odyssey to Mount Ararat and Beyond
Four
Frostbite (Vampire Academy #2)
Five
Follow You Home
One
First Steps for New Christians (Print Edition)
One
Finders Keepers (Bill Hodges Trilogy #2)
Five
Fables, Vol. 1: Legends in Exile (Fables #1)
Four
Eureka Trivia 6.0
Four
Drive: The Surprising Truth About What Motivates Us
Four
Done Rubbed Out (Reightman & Bailey #1)
Five
Doing It Over (Most Likely To #1)
Three
Deliciously Ella Every Day: Quick and Easy Recipes for Gluten-Free Snacks, Packed Lunches, and Simple Meals
Three
Dark Notes
Five
Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead
Three
Close to You
Four
Chasing Heaven: What Dying Taught Me About Living
Two
Big Magic: Creative Living Beyond Fear
Three
Becoming Wise: An Inquiry into the Mystery and Art of Living
Two
Beauty Restored (Riley Family Legacy Novellas #3)
Two
Batman: The Long Halloween (Batman)
Two
Batman: The Dark Knight Returns (Batman)
Five
Ayumi's Violin
Two
Anonymous
Four
Amy Meets the Saints and Sages
Three
Amid the Chaos
One
Amatus
Five
Agnostic: A Spirited Manifesto
Five
Zealot: The Life and Times of Jesus of Nazareth
Three
You (You #1)
Five
Wonder Woman: Earth One, Volume One (Wonder Woman: Earth One #1)
Four
Wild Swans
Two
Why the Right Went Wrong: Conservatism--From Goldwater to the Tea Party and Beyond
Four
Whole Lotta Creativity Going On: 60 Fun and Unusual Exercises to Awaken and Strengthen Your Creativity
Four
What's It Like in Space?: Stories from Astronauts Who've Been There
Two
We Are Robin, Vol. 1: The Vigilante Business (We Are Robin #1)
One
Walt Disney's Alice in Wonderland
Five
V for Vendetta (V for Vendetta Complete)
Four
Until Friday Night (The Field Party #1)
Two
Unbroken: A World War II Story of Survival, Resilience, and Redemption
Two
Twenty Yawns
Two
Through the Woods
Two
This Is Where It Ends
Two
The Year of Magical Thinking
Two
The Wright Brothers
Four
The White Queen (The Cousins' War #1)
Five
The Wedding Pact (The O'Malleys #2)
Three
The Time Keeper
Five
The Testament of Mary
Four
The Star-Touched Queen
Five
The Songs of the Gods
Five
The Song of Achilles
Five
The Rosie Project (Don Tillman #1)
One
The Power of Habit: Why We Do What We Do in Life and Business
Three
The Marriage of Opposites
Four
The Lucifer Effect: Understanding How Good People Turn Evil
One
The Long Haul (Diary of a Wimpy Kid #9)
One
The Loney
One
The Literature Book (Big Ideas Simply Explained)
Three
The Last Mile (Amos Decker #2)
Two
The Immortal Life of Henrietta Lacks
Two
The Hidden Oracle (The Trials of Apollo #1)
Two
The Help Yourself Cookbook for Kids: 60 Easy Plant-Based Recipes Kids Can Make to Stay Healthy and Save the Earth
Three
The Guilty (Will Robie #4)
Two
The First Hostage (J.B. Collins #2)
Three
The Dovekeepers
One
The Darkest Lie
Five
The Bane Chronicles (The Bane Chronicles #1-11)
Four
The Bad-Ass Librarians of Timbuktu: And Their Race to Save the World’s Most Precious Manuscripts
One
The 14th Colony (Cotton Malone #11)
One
That Darkness (Gardiner and Renner #1)
One
Tastes Like Fear (DI Marnie Rome #3)
One
Take Me with You
Three
Swell: A Year of Waves
One
Superman Vol. 1: Before Truth (Superman by Gene Luen Yang #1)
Five
Still Life with Bread Crumbs
Three
Steve Jobs
Five
Sorting the Beef from the Bull: The Science of Food Fraud Forensics
Four
Someone Like You (The Harrisons #2)
Five
So Cute It Hurts!!, Vol. 6 (So Cute It Hurts!! #6)
Four
Shtum
Four
See America: A Celebration of Our National Parks & Treasured Sites
Three
salt.
Four
Robin War
Three
Red Hood/Arsenal, Vol. 1: Open for Business (Red Hood/Arsenal #1)
Two
Rain Fish
Three
Quarter Life Poetry: Poems for the Young, Broke and Hangry
Five
Pet Sematary
Three
Overload: How to Unplug, Unwind, and Unleash Yourself from the Pressure of Stress
Three
Once Was a Time
Two
Old School (Diary of a Wimpy Kid #10)
Five
No Dream Is Too High: Life Lessons From a Man Who Walked on the Moon
Two
Naruto (3-in-1 Edition), Vol. 14: Includes Vols. 40, 41 & 42 (Naruto: Omnibus #14)
Two
My Name Is Lucy Barton
One
My Mrs. Brown
Three
My Kind of Crazy
One
Mr. Mercedes (Bill Hodges Trilogy #1)
One
More Than Music (Chasing the Dream #1)
Two
Made to Stick: Why Some Ideas Survive and Others Die
Five
Luis Paints the World
Three
Luckiest Girl Alive
Three
Lowriders to the Center of the Earth (Lowriders in Space #2)
Two
Love Is a Mix Tape (Music #1)
One
Looking for Lovely: Collecting the Moments that Matter
Five
Living Leadership by Insight: A Good Leader Achieves, a Great Leader Builds Monuments
Four
Let It Out: A Journey Through Journaling
Five
Lady Midnight (The Dark Artifices #1)
Five
It's All Easy: Healthy, Delicious Weeknight Meals in under 30 Minutes
One
Island of Dragons (Unwanteds #7)
One
I Know What I'm Doing -- and Other Lies I Tell Myself: Dispatches from a Life Under Construction
Four
I Am Pilgrim (Pilgrim #1)
Four
Hyperbole and a Half: Unfortunate Situations, Flawed Coping Mechanisms, Mayhem, and Other Things That Happened
Five
Hush, Hush (Hush, Hush #1)
Three
Hold Your Breath (Search and Rescue #1)
One
Hamilton: The Revolution
Three
Greek Mythic History
Five
God: The Most Unpleasant Character in All Fiction
Five
Glory over Everything: Beyond The Kitchen House
Three
Feathers: Displays of Brilliant Plumage
Three
Far & Away: Places on the Brink of Change: Seven Continents, Twenty-Five Years
Four
Every Last Word
Three
Eligible (The Austen Project #4)
Three
El Deafo
Five
Eight Hundred Grapes
Four
Eaternity: More than 150 Deliciously Easy Vegan Recipes for a Long, Healthy, Satisfied, Joyful Life
Five
Eat Fat, Get Thin
Two
Don't Get Caught
One
Doctor Sleep (The Shining #2)
Two
Demigods & Magicians: Percy and Annabeth Meet the Kanes (Percy Jackson & Kane Chronicles Crossover #1-3)
Five
Dear Mr. Knightley
Five
Daily Fantasy Sports
One
Crazy Love: Overwhelmed by a Relentless God
Two
Cometh the Hour (The Clifton Chronicles #6)
Three
Code Name Verity (Code Name Verity #1)
Four
Clockwork Angel (The Infernal Devices #1)
One
City of Glass (The Mortal Instruments #3)
Four
City of Fallen Angels (The Mortal Instruments #4)
Four
City of Bones (The Mortal Instruments #1)
One
City of Ashes (The Mortal Instruments #2)
One
Cell
Four
Catching Jordan (Hundred Oaks)
Three
Carry On, Warrior: Thoughts on Life Unarmed
Three
Carrie
Two
Buying In: The Secret Dialogue Between What We Buy and Who We Are
Four
Brain on Fire: My Month of Madness
Five
Batman: Europa
Two
Barefoot Contessa Back to Basics
One
Barefoot Contessa at Home: Everyday Recipes You'll Make Over and Over Again
Five
Balloon Animals
Three
Art Ops Vol. 1
Three
Aristotle and Dante Discover the Secrets of the Universe (Aristotle and Dante Discover the Secrets of the Universe #1)
Four
Angels Walking (Angels Walking #1)
Two
Angels & Demons (Robert Langdon #1)
Three
All the Light We Cannot See
Five
Adulthood Is a Myth: A "Sarah's Scribbles" Collection
Two
Abstract City
Five
A Time of Torment (Charlie Parker #14)
Five
A Study in Scarlet (Sherlock Holmes #1)
Two
A Series of Catastrophes and Miracles: A True Story of Love, Science, and Cancer
Two
A People's History of the United States
Two
A Man Called Ove
One
A Distant Mirror: The Calamitous 14th Century
Three
A Brush of Wings (Angels Walking #3)
One
1491: New Revelations of the Americas Before Columbus
Three
The Three Searches, Meaning, and the Story
Three
Searching for Meaning in Gailana
One
Rook
Four
My Kitchen Year: 136 Recipes That Saved My Life
Two
13 Hours: The Inside Account of What Really Happened In Benghazi
One
Will You Won't You Want Me?
Three
Tipping Point for Planet Earth: How Close Are We to the Edge?
One
The Star-Touched Queen
Five
The Silent Sister (Riley MacPherson #1)
Five
The Midnight Watch: A Novel of the Titanic and the Californian
One
The Lonely City: Adventures in the Art of Being Alone
Two
The Gray Rhino: How to Recognize and Act on the Obvious Dangers We Ignore
Four
The Golden Condom: And Other Essays on Love Lost and Found
One
The Epidemic (The Program 0.6)
Five
The Dinner Party
Two
The Diary of a Young Girl
Three
The Children
Three
Stars Above (The Lunar Chronicles #4.5)
Two
Snatched: How A Drug Queen Went Undercover for the DEA and Was Kidnapped By Colombian Guerillas
Three
Raspberry Pi Electronics Projects for the Evil Genius
Four
Quench Your Own Thirst: Business Lessons Learned Over a Beer or Two
One
Psycho: Sanitarium (Psycho #1.5)
Five
Poisonous (Max Revere Novels #3)
Three
One with You (Crossfire #5)
Four
No Love Allowed (Dodge Cove #1)
Four
Murder at the 42nd Street Library (Raymond Ambler #1)
Four
Most Wanted
Three
Love, Lies and Spies
Two
How to Speak Golf: An Illustrated Guide to Links Lingo
Five
Hide Away (Eve Duncan #20)
One
Furiously Happy: A Funny Book About Horrible Things
Four
Everyday Italian: 125 Simple and Delicious Recipes
Five
Equal Is Unfair: America's Misguided Fight Against Income Inequality
One
Eleanor & Park
Five
Dirty (Dive Bar #1)
Four
Can You Keep a Secret? (Fear Street Relaunch #4)
One
Boar Island (Anna Pigeon #19)
Three
A Paris Apartment
Four
A la Mode: 120 Recipes in 60 Pairings: Pies, Tarts, Cakes, Crisps, and More Topped with Ice Cream, Gelato, Frozen Custard, and More
One
Troublemaker: Surviving Hollywood and Scientology
Two
The Widow
Two
The Sleep Revolution: Transforming Your Life, One Night at a Time
Four
The Improbability of Love
One
The Art of Startup Fundraising
Three
Take Me Home Tonight (Rock Star Romance #3)
Three
Sleeping Giants (Themis Files #1)
One
Setting the World on Fire: The Brief, Astonishing Life of St. Catherine of Siena
Two
Playing with Fire
Three
Off the Hook (Fishing for Trouble #1)
Three
Mothering Sunday
Two
Mother, Can You Not?
Five
M Train
One
Lilac Girls
Two
Lies and Other Acts of Love
One
Lab Girl
One
Keep Me Posted
Four
It Didn't Start with You: How Inherited Family Trauma Shapes Who We Are and How to End the Cycle
Three
Grey (Fifty Shades #4)
Four
Exit, Pursued by a Bear
Four
Daredevils
Three
Cravings: Recipes for What You Want to Eat
Three
Born for This: How to Find the Work You Were Meant to Do
Five
Arena
Four
Adultery
Five
A Mother's Reckoning: Living in the Aftermath of Tragedy
Three
A Gentleman's Position (Society of Gentlemen #3)
Five
11/22/63
Three
10% Happier: How I Tamed the Voice in My Head, Reduced Stress Without Losing My Edge, and Found Self-Help That Actually Works
Two
10-Day Green Smoothie Cleanse: Lose Up to 15 Pounds in 10 Days!
Five
Without Shame
Five
Watchmen
Four
Unlimited Intuition Now
Four
Underlying Notes
Two
The Shack
One

## Một cách khác mà không cần dùng vòng for, một số trường hợp url sẽ không có trọng số chứa số trang

In [ ]:
import requests as re
import pandas as pd
from bs4 import BeautifulSoup

In [ ]:
url = "https://books.toscrape.com/catalogue/page-1.html"

In [ ]:

while True:
   r = re.get(url)
   soup = BeautifulSoup(r.text, 'html.parser')
   next = soup.find('li', class_ = 'next')

   if next:  # Nếu tìm thấy phần tử <li class="next">
      next_link = next.find('a').attrs['href']
      url = 'https://books.toscrape.com/catalogue/' + next_link
      print(next_link, f" Url tương ứng : f{url}")
   else:
      print("Không tìm thấy nút Next trên trang này.")
      break

page-2.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-2.html
page-3.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-3.html
page-4.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-4.html
page-5.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-5.html
page-6.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-6.html
page-7.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-7.html
page-8.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-8.html
page-9.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-9.html
page-10.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-10.html
page-11.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-11.html
page-12.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-12.html
page-13.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-13.html
page-14.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-14.html
page-15.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-15.html
page-16.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-16.html
page-17.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-17.html
page-18.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-18.html
page-19.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-19.html
page-20.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-20.html
page-21.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-21.html
page-22.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-22.html
page-23.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-23.html
page-24.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-24.html
page-25.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-25.html
page-26.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-26.html
page-27.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-27.html
page-28.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-28.html
page-29.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-29.html
page-30.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-30.html
page-31.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-31.html
page-32.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-32.html
page-33.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-33.html
page-34.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-34.html
page-35.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-35.html
page-36.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-36.html
page-37.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-37.html
page-38.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-38.html
page-39.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-39.html
page-40.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-40.html
page-41.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-41.html
page-42.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-42.html
page-43.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-43.html
page-44.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-44.html
page-45.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-45.html
page-46.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-46.html
page-47.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-47.html
page-48.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-48.html
page-49.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-49.html
page-50.html  Url tương ứng : fhttps://books.toscrape.com/catalogue/page-50.html
Không tìm thấy nút Next trên trang này.

# Extract Data from Airbnb Delhi😮

In [1]:
import requests as re
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url = "https://www.airbnb.co.in/s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1"
r = re.get(url)

In [3]:
print(r.status_code)
soup = BeautifulSoup(r.content, 'html.parser')

200

In [4]:
table = soup.find_all('div', class_ = "gsgwcjk atm_10yczz8_kb7nvz atm_10yczz8_cs5v99__1ldigyt atm_10yczz8_11wpgbn__1v156lz atm_10yczz8_egatvm__qky54b atm_10yczz8_qfx8er__1xolj55 atm_10yczz8_ouytup__w5e62l g8ge8f1 atm_1d13e1y_p5ox87 atm_yrukzc_1od0ugv atm_10yczz8_cs5v99_vagkz0_1ldigyt atm_10yczz8_11wpgbn_vagkz0_1h2hqoz g14v8520 atm_9s_11p5wf0 atm_d5_j5tqy atm_d7_1ymvx20 atm_dl_1mvrszh atm_dz_hxz02 dir dir-ltr")
len(table)

1

In [5]:
div = table[0].find_all('div', class_ = "c1l1h97y atm_d2_1kqhmmj dir dir-ltr")
print(len(div))

18

In [6]:
for d in div:
  link = d.find_all('div', class_ = "cy5jw6o atm_5j_223wjw atm_70_87waog atm_j3_1u6x1zy atm_jb_4shrsx atm_mk_h2mmj6 atm_vy_7abht0 dir dir-ltr")
  link = link[0].find('a')
  print("https://www.airbnb.co.in/" + link.attrs['href'])

https://www.airbnb.co.in//rooms/1204251501209755375?adults=1&search_mode=regular_search&check_in=2025-05-19&check_out=2025-05-24&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3GvwcJHpA4WX0bE&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/10384839?adults=1&search_mode=regular_search&check_in=2025-04-20&check_out=2025-04-25&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3FfqrEefUYhG0D3&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/956325156020381225?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=1892769507&source_impression_id=p3_1742741674_P3srfELypmgnhGa3&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/6076545?adults=1&search_mode=regular_search&check_in=2025-04-08&check_out=2025-04-13&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3eucvPWHgF6TFt6&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/1329549308940563784?adults=1&search_mode=regular_search&check_in=2025-04-16&check_out=2025-04-21&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3HY9XJ6MRhr-JX_&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/17768423?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&photo_id=756552631&source_impression_id=p3_1742741674_P36zo97DYwgCBcWq&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/39095592?adults=1&search_mode=regular_search&check_in=2025-04-16&check_out=2025-04-21&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3Dmw89NagyVe7-K&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/27592434?adults=1&search_mode=regular_search&check_in=2025-04-27&check_out=2025-05-02&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3zyWDZ-4_eZYXKm&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/491208?adults=1&search_mode=regular_search&check_in=2025-05-03&check_out=2025-05-08&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3iv9JraFYg9bXq9&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/1023638459683285709?adults=1&search_mode=regular_search&check_in=2025-04-30&check_out=2025-05-05&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3TilLgkFsF68XHD&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/17231611?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-22&check_out=2025-04-27&children=0&infants=0&pets=0&photo_id=1680676955&source_impression_id=p3_1742741674_P3QLnWOT9ZfLXLJf&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/39836406?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-20&check_out=2025-04-25&children=0&infants=0&pets=0&photo_id=1537397106&source_impression_id=p3_1742741674_P3BIjyHFjSOyzGOK&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/7284631?adults=1&search_mode=regular_search&check_in=2025-05-03&check_out=2025-05-08&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3BJbSTZisFK1T-0&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/40559421?adults=1&search_mode=regular_search&check_in=2025-05-03&check_out=2025-05-08&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3ZHShFEYglzgAK1&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/980254140695736726?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-03&check_out=2025-04-08&children=0&infants=0&pets=0&photo_id=1820144041&source_impression_id=p3_1742741674_P3p3kmDrCi9eM4rE&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/1049921900317350385?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-07&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3jtOQW-R8QZO_96&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/1151182876971419975?adults=1&search_mode=regular_search&check_in=2025-05-07&check_out=2025-05-12&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P3A9_w9CAQi9E67Z&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112
https://www.airbnb.co.in//rooms/1218095137465591523?adults=1&search_mode=regular_search&check_in=2025-04-08&check_out=2025-04-13&children=0&infants=0&pets=0&source_impression_id=p3_1742741674_P38xk871yFBdsZ82&previous_page_section_name=1000&federated_search_id=c7da8c3e-4137-4f32-906e-706fcdf7d112

In [7]:
url = "https://www.airbnb.co.in/s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjowLCJ2ZXJzaW9uIjoxfQ%3D%3D"
list_page = []
while True:
  list_page.append(url)
  r = re.get(url)
  soup = BeautifulSoup(r.content, 'html.parser')


  table = soup.find_all('div', class_ = "gsgwcjk atm_10yczz8_kb7nvz atm_10yczz8_cs5v99__1ldigyt atm_10yczz8_11wpgbn__1v156lz atm_10yczz8_egatvm__qky54b atm_10yczz8_qfx8er__1xolj55 atm_10yczz8_ouytup__w5e62l g8ge8f1 atm_1d13e1y_p5ox87 atm_yrukzc_1od0ugv atm_10yczz8_cs5v99_vagkz0_1ldigyt atm_10yczz8_11wpgbn_vagkz0_1h2hqoz g14v8520 atm_9s_11p5wf0 atm_d5_j5tqy atm_d7_1ymvx20 atm_dl_1mvrszh atm_dz_hxz02 dir dir-ltr")
  div = table[0].find_all('div', class_ = "c1l1h97y atm_d2_1kqhmmj dir dir-ltr")

  for d in div:
    link = d.find_all('div', class_ = "cy5jw6o atm_5j_223wjw atm_70_87waog atm_j3_1u6x1zy atm_jb_4shrsx atm_mk_h2mmj6 atm_vy_7abht0 dir dir-ltr")
    link = link[0].find('a')
    print("https://www.airbnb.co.in/" + link.attrs['href'])

  base = "https://www.airbnb.co.in/"


  next_page = soup.find_all('div', class_ = "p1j2gy66 atm_9s_1txwivl dir dir-ltr")

  next_page = next_page[0].find('a', class_  =  "l1ovpqvx atm_1he2i46_1k8pnbi_10saat9 atm_yxpdqi_1pv6nv4_10saat9 atm_1a0hdzc_w1h1e8_10saat9 atm_2bu6ew_929bqk_10saat9 atm_12oyo1u_73u7pn_10saat9 atm_fiaz40_1etamxe_10saat9 c1ytbx3a atm_mk_h2mmj6 atm_9s_1txwivl atm_h_1h6ojuz atm_fc_1h6ojuz atm_bb_idpfg4 atm_26_1j28jx2 atm_3f_glywfm atm_7l_hkljqm atm_gi_idpfg4 atm_l8_idpfg4 atm_uc_10d7vwn atm_kd_glywfm atm_gz_8tjzot atm_uc_glywfm__1rrf6b5 atm_26_zbnr2t_1rqz0hn_uv4tnr atm_tr_kv3y6q_csw3t1 atm_26_zbnr2t_1ul2smo atm_3f_glywfm_jo46a5 atm_l8_idpfg4_jo46a5 atm_gi_idpfg4_jo46a5 atm_3f_glywfm_1icshfk atm_kd_glywfm_19774hq atm_70_glywfm_1w3cfyq atm_uc_aaiy6o_9xuho3 atm_70_18bflhl_9xuho3 atm_26_zbnr2t_9xuho3 atm_uc_glywfm_9xuho3_1rrf6b5 atm_70_glywfm_pfnrn2_1oszvuo atm_uc_aaiy6o_1buez3b_1oszvuo atm_70_18bflhl_1buez3b_1oszvuo atm_26_zbnr2t_1buez3b_1oszvuo atm_uc_glywfm_1buez3b_1o31aam atm_7l_1wxwdr3_1o5j5ji atm_9j_13gfvf7_1o5j5ji atm_26_1j28jx2_154oz7f atm_92_1yyfdc7_vmtskl atm_9s_1ulexfb_vmtskl atm_mk_stnw88_vmtskl atm_tk_1ssbidh_vmtskl atm_fq_1ssbidh_vmtskl atm_tr_pryxvc_vmtskl atm_vy_1vi7ecw_vmtskl atm_e2_1vi7ecw_vmtskl atm_5j_1ssbidh_vmtskl atm_mk_h2mmj6_1ko0jae dir dir-ltr")


  if next_page:
    add = next_page.attrs['href']
    url = base + add
  else:
    print("Không còn page nào nữa !")
    break

https://www.airbnb.co.in//rooms/1000706845935077758?adults=1&search_mode=regular_search&check_in=2025-04-21&check_out=2025-04-26&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3e0OIQSQ-GfqzyA&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1130363303644074683?adults=1&search_mode=regular_search&check_in=2025-04-30&check_out=2025-05-05&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3K5ttfspGGutmht&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/841015470655650057?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3BuRoJygFE0DH6H&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/54030159?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-19&check_out=2025-04-24&children=0&infants=0&pets=0&photo_id=1346738881&source_impression_id=p3_1742741676_P3cB8Xd970WeSRaW&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1350045229573516174?adults=1&search_mode=regular_search&check_in=2025-05-02&check_out=2025-05-07&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3Ym6RSqocP3tIaw&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1058636977721195727?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3YE49X3Jhh3FAH_&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/47399895?adults=1&search_mode=regular_search&check_in=2025-04-16&check_out=2025-04-21&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3HfcljN_ZKESmJg&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/52915665?adults=1&search_mode=regular_search&check_in=2025-04-06&check_out=2025-04-11&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P38-dKRppHXs2Ghl&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1104193328193078950?adults=1&search_mode=regular_search&check_in=2025-04-20&check_out=2025-04-25&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3wWrSkhXXK-wnOs&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/50685295?adults=1&search_mode=regular_search&check_in=2025-04-29&check_out=2025-05-04&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P373GUV50YfB65CS&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1334426220061571563?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=2076603749&source_impression_id=p3_1742741676_P37AqODgZo-CmLjk&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/46522465?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P33I6h-ZNBE7SAnJ&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1206637568604298724?adults=1&search_mode=regular_search&check_in=2025-04-06&check_out=2025-04-11&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3_C-qHFUBB8-gTU&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/8918735?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=1581504026&source_impression_id=p3_1742741676_P3Cw9Sbl9ZdXJGcD&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1358870805136158132?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3hNtM9Qzbbkz3pH&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1348336340814169992?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P3-ZJsBAUin7Zolt&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/45554190?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=1071561544&source_impression_id=p3_1742741676_P38ks12oIjPbNOr5&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/4664756?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741676_P37_IuJx87O8Sw7W&previous_page_section_name=1000&federated_search_id=8976c94e-0b96-47bf-abbe-e458b2f3a0b9
https://www.airbnb.co.in//rooms/1196313109504697548?adults=1&search_mode=regular_search&check_in=2025-04-06&check_out=2025-04-11&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3hxkTU2zTXeU_LY&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1110041048351966712?adults=1&search_mode=regular_search&check_in=2025-04-04&check_out=2025-04-09&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3ZS8iHGHDsT-zU0&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/640199830524957959?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3luUsU9_ih_OFRQ&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/15426119?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-10&check_out=2025-04-15&children=0&infants=0&pets=0&photo_id=220060577&source_impression_id=p3_1742741678_P3QgLslb7AIOVXgJ&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1275143290303455601?adults=1&search_mode=regular_search&check_in=2025-05-04&check_out=2025-05-09&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3GG_9GUGTgcTdk5&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1270231479729229938?adults=1&search_mode=regular_search&check_in=2025-05-05&check_out=2025-05-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P33OhN62RUD6lPUO&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/50685295?adults=1&search_mode=regular_search&check_in=2025-04-29&check_out=2025-05-04&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3zfH8NiHQV-IwGe&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1192160113078643595?adults=1&search_mode=regular_search&check_in=2025-04-12&check_out=2025-04-17&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3Vm8-QJfSOobwZ2&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1325436810000762827?adults=1&search_mode=regular_search&check_in=2025-04-15&check_out=2025-04-20&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3_XYJQz-gxsHLwH&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1049177012641549401?adults=1&search_mode=regular_search&check_in=2025-04-04&check_out=2025-04-09&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P39F1jdlKiDnGlhn&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1058636977721195727?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3KQ41Pr54wevET9&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1342419085967420437?adults=1&search_mode=regular_search&check_in=2025-04-20&check_out=2025-04-25&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3Nm6vRuA1sSktOW&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1146171552329837461?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3mK1SQobBK-29AS&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/50822977?adults=1&search_mode=regular_search&check_in=2025-04-02&check_out=2025-04-07&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3Mq2nD7hxMJE_D9&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1241081581561394185?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3Qu7XV7AWF3pgcU&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/53142121?adults=1&search_mode=regular_search&check_in=2025-04-20&check_out=2025-04-25&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3H4fze8cxj3zBDP&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/8918735?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=1581504026&source_impression_id=p3_1742741678_P3O69qryHLeaSMMK&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/13380582?adults=1&search_mode=regular_search&check_in=2025-04-10&check_out=2025-04-15&children=0&infants=0&pets=0&source_impression_id=p3_1742741678_P3-z3zgE2eTKV8ga&previous_page_section_name=1000&federated_search_id=23a78a08-bb89-4fbb-927a-d9d9a079c655
https://www.airbnb.co.in//rooms/1145681289184756273?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3KOORehnpeL1D_M&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/581453311303306869?adults=1&search_mode=regular_search&check_in=2025-04-19&check_out=2025-04-24&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3poHzp7Mdaw1Zco&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/51072039?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3Op8-nBI5UftaOe&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/50822977?adults=1&search_mode=regular_search&check_in=2025-04-02&check_out=2025-04-07&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3YDmtGTP9uvxcxY&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/15426119?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-10&check_out=2025-04-15&children=0&infants=0&pets=0&photo_id=220060577&source_impression_id=p3_1742741679_P3Qv3VgLc-r-Z1L8&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1235872661430112064?adults=1&search_mode=regular_search&check_in=2025-05-12&check_out=2025-05-17&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3ulHfj1RjQRBm5E&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1199679747034091070?adults=1&search_mode=regular_search&check_in=2025-04-08&check_out=2025-04-13&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3Sjj7LM0xyXF4Fm&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1066019088114569689?adults=1&search_mode=regular_search&check_in=2025-04-12&check_out=2025-04-17&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P34x5oE5fCHdpnqJ&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1263063191755786170?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3cXrFCGAh50k-w_&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1050345618468077223?adults=1&search_mode=regular_search&check_in=2025-04-17&check_out=2025-04-22&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3Jvs61kGBfSd2OA&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1241081581561394185?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3KHxg9dV86SkbDB&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1196313109504697548?adults=1&search_mode=regular_search&check_in=2025-04-06&check_out=2025-04-11&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3sgPiT4_yiAkGXx&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/568371865221488640?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3kq7QqYH3ZRwudo&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1110041048351966712?adults=1&search_mode=regular_search&check_in=2025-04-04&check_out=2025-04-09&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3HIo5gglGPCkIwH&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/49741019?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3JVZ43C1JO47WJg&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1330822304784553852?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-03&check_out=2025-04-08&children=0&infants=0&pets=0&photo_id=2082213325&source_impression_id=p3_1742741679_P3LaIYgBMUyDzgIM&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/51072701?adults=1&search_mode=regular_search&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&source_impression_id=p3_1742741679_P3P4RQSor8jSgMN7&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1292680866740742988?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=2032373250&source_impression_id=p3_1742741679_P3CLG9XYa98FYlYu&previous_page_section_name=1000&federated_search_id=db62828c-8c4b-4304-a49c-948e4c053776
https://www.airbnb.co.in//rooms/1330822304784553852?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-03&check_out=2025-04-08&children=0&infants=0&pets=0&photo_id=2082213325&source_impression_id=p3_1742741681_P3Yftbrcu9PHsqH5&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/51935866?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-15&check_out=2025-04-20&children=0&infants=0&pets=0&photo_id=1519730663&source_impression_id=p3_1742741681_P3hKkR-af8DUAtt5&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1204458150280333791?adults=1&search_mode=regular_search&check_in=2025-04-25&check_out=2025-04-30&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3t_OXe4g7byieaT&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1292680866740742988?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-01&check_out=2025-04-06&children=0&infants=0&pets=0&photo_id=2032373250&source_impression_id=p3_1742741681_P3DJyVhxMfDDA3kj&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1344990885148866230?adults=1&search_mode=regular_search&category_tag=Tag%3A8678&check_in=2025-04-22&check_out=2025-04-27&children=0&infants=0&pets=0&photo_id=2097741551&source_impression_id=p3_1742741681_P3UFI4yix61XYt6q&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/993756841254487580?adults=1&search_mode=regular_search&check_in=2025-04-13&check_out=2025-04-18&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3VkpNEp2j1i1U7o&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1259942929662348274?adults=1&search_mode=regular_search&check_in=2025-04-14&check_out=2025-04-19&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P37Sw_7NrfjceyHH&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1272400326403234342?adults=1&search_mode=regular_search&check_in=2025-04-11&check_out=2025-04-16&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3wv9sW2-o6c9eFE&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1195393444109327298?adults=1&search_mode=regular_search&check_in=2025-04-12&check_out=2025-04-17&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3ddtitwkyz2nTBC&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/915901503094760091?adults=1&search_mode=regular_search&check_in=2025-04-07&check_out=2025-04-12&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3BgYt1m9nxdE1iA&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/51071329?adults=1&search_mode=regular_search&check_in=2025-04-05&check_out=2025-04-10&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3FvoNsxwe3mDVMS&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9
https://www.airbnb.co.in//rooms/1059071503510323732?adults=1&search_mode=regular_search&check_in=2025-04-04&check_out=2025-04-09&children=0&infants=0&pets=0&source_impression_id=p3_1742741681_P3xb4iw2jqFK2hnN&previous_page_section_name=1000&federated_search_id=6d9d55d5-8ab1-4020-97ba-0db5ac9760e9

In [168]:
columns = ['Name', 'Description', 'Price']


datafr = pd.DataFrame(columns = columns)
datafr

Empty DataFrame
Columns: [Name, Description, Price]
Index: []

In [14]:
list_page

['https://www.airbnb.co.in/s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjowLCJ2ZXJzaW9uIjoxfQ%3D%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxOCwidmVyc2lvbiI6MX0%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjozNiwidmVyc2lvbiI6MX0%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0Ijo1NCwidmVyc2lvbiI6MX0%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0Ijo3MiwidmVyc2lvbiI6MX0%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0Ijo5MCwidmVyc2lvbiI6MX0%3D',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxMDgsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxMjYsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxNDQsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxNjIsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxODAsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoxOTgsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoyMTYsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoyMzQsInZlcnNpb24iOjF9',
 'https://www.airbnb.co.in//s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjoyNTIsInZlcnNpb24iOjF9']

## Data_to_csv

In [117]:
list_page[0]

'https://www.airbnb.co.in/s/New-Delhi--India/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJLbZ-NFv9DDkRzk0gTkm3wlI&adults=1&query=New%20Delhi%2C%20India&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2025-04-01&monthly_length=3&monthly_end_date=2025-07-01&search_mode=regular_search&price_filter_input_type=0&channel=EXPLORE&ne_lat=31.570634900876296&ne_lng=79.60203414970056&sw_lat=25.525926019984208&sw_lng=77.29712767407489&zoom=7.823392099275787&zoom_level=7&search_by_map=true&search_type=user_map_move&price_filter_num_nights=5&pagination_search=true&federated_search_session_id=152003ee-92e0-476e-ba06-934c38eb1f09&cursor=eyJzZWN0aW9uX29mZnNldCI6MCwiaXRlbXNfb2Zmc2V0IjowLCJ2ZXJzaW9uIjoxfQ%3D%3D'

In [151]:
url = list_page[4]
r = re.get(url)
soup = BeautifulSoup(r.text, 'html.parser')

In [152]:
table = soup.find_all('div', class_ = "gsgwcjk atm_10yczz8_kb7nvz atm_10yczz8_cs5v99__1ldigyt atm_10yczz8_11wpgbn__1v156lz atm_10yczz8_egatvm__qky54b atm_10yczz8_qfx8er__1xolj55 atm_10yczz8_ouytup__w5e62l g8ge8f1 atm_1d13e1y_p5ox87 atm_yrukzc_1od0ugv atm_10yczz8_cs5v99_vagkz0_1ldigyt atm_10yczz8_11wpgbn_vagkz0_1h2hqoz g14v8520 atm_9s_11p5wf0 atm_d5_j5tqy atm_d7_1ymvx20 atm_dl_1mvrszh atm_dz_hxz02 dir dir-ltr")

In [146]:
len(table)

1

In [153]:
data = table[0].find_all('div', class_ = "g1qv1ctd atm_u80d3j_1li1fea atm_c8_o7aogt atm_g3_8jkm7i c1v0rf5q atm_9s_11p5wf0 atm_cx_4wguik atm_dz_7esijk atm_e0_1lo05zz dir dir-ltr")

In [154]:
len(data)

18

In [155]:
for d in data:
  name = d.find('div', class_ = "t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_10d11i2 atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr")
  des = d.find('span', class_ = "t6mzqp7 atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_kb7nvz atm_7l_1he744i atm_am_qk3dho atm_ks_zryt35__1rgatj2 dir dir-ltr")
  price = d.find('span', class_ = "_hb913q")


  print(name.text, des.text, price.text)

Place to stay in Mussoorie Retreat by The Kiana's ₹9,699
Flat in Noida Pebble spot ₹3,814
Home in Noida Luxury Apartment -Jaypee Wishtown Noida (PRIVATE) ₹4,005
Campsite in Rishikesh Nature Camp on Neer waterfall,Neerville,Rishikesh. ₹1,163
Home in Dehradun Kim Ori Kim -cosy 2bhk with balcony on 1st floor ₹2,739
Room in Nainital The Cullinan House - “The Hope” ₹3,000
Room in Noida Gulmohar ₹1,726
Home in Vrindavan Vraj ₹1,700
Room in Noida Noida Large Suite + en-suite (private Bathroom) ₹2,295
Place to stay in Lam Kande KeeKoo kanatal,Wealthinwhite ₹12,400
Room in Noida O-Space ₹1,716
Place to stay in Ranikhet 10, Nautical Miles -Mountain Cottage of a Mariner ₹3,424
Apartment in Noida Studio3 PvtEntrn Kitchn Balcny NoidaSec18Metro650m ₹1,291
Place to stay in Noida Independent apartment with a garden in city centre ₹2,394
Apartment in Noida BluO Penthouse, BathTub, Terrace Garden#Staycation ₹6,380
Home in Noida Corner Villa Ground-Floor ₹2,853
Flat in Delhi Homlee-Best Value flat with kitchen Near Metro ₹1,590
Guest suite in Dehradun Laid-back Budget Homestay in Dalanwala ₹1,488

In [169]:
for url in list_page:
  r = re.get(url)
  soup = BeautifulSoup(r.content, 'html.parser')
  table = soup.find_all('div', class_ = "gsgwcjk atm_10yczz8_kb7nvz atm_10yczz8_cs5v99__1ldigyt atm_10yczz8_11wpgbn__1v156lz atm_10yczz8_egatvm__qky54b atm_10yczz8_qfx8er__1xolj55 atm_10yczz8_ouytup__w5e62l g8ge8f1 atm_1d13e1y_p5ox87 atm_yrukzc_1od0ugv atm_10yczz8_cs5v99_vagkz0_1ldigyt atm_10yczz8_11wpgbn_vagkz0_1h2hqoz g14v8520 atm_9s_11p5wf0 atm_d5_j5tqy atm_d7_1ymvx20 atm_dl_1mvrszh atm_dz_hxz02 dir dir-ltr")
  data = table[0].find_all('div', class_ = "g1qv1ctd atm_u80d3j_1li1fea atm_c8_o7aogt atm_g3_8jkm7i c1v0rf5q atm_9s_11p5wf0 atm_cx_4wguik atm_dz_7esijk atm_e0_1lo05zz dir dir-ltr")
  for d in data:
    name = d.find('div', class_ = "t1jojoys atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_1vgr820 atm_7l_jt7fhx atm_cs_10d11i2 atm_w4_1eetg7c atm_ks_zryt35__1rgatj2 dir dir-ltr")
    des = d.find('span', class_ = "t6mzqp7 atm_g3_1kw7nm4 atm_ks_15vqwwr atm_sq_1l2sidv atm_9s_cj1kg8 atm_6w_1e54zos atm_fy_kb7nvz atm_7l_1he744i atm_am_qk3dho atm_ks_zryt35__1rgatj2 dir dir-ltr")
    price = d.find('span', class_ = "_hb913q")
    name_text = name.text if name else None
    des_text = des.text if des else None
    price_text = price.text if price else None

    print(name_text, des_text, price_text)
    datafr.loc[len(datafr)] = [name_text, des_text, price_text]

Room in Noida HomeStay Premium for Professionals None
Earthen home in Rishikesh Hand-Sculpted Fairytale Forest Villa (Entire home) None
Place to stay in Rakchham Folktales ; Co-Living space & Artist Retreat None
Dome in Cheog Glamo Home Cheog , Shimla None
Cabin in Mussoorie Cozy Cabin with Private Deck in Landour! None
Flat in Vrindavan Krishna's Braj None
Cabin in Sukha Glass Lodge Himalaya - EKAA None
Boutique hotel in Agra Deluxe Double Room /200 Mtrs from Tajmahal Parking None
Hut in Uttarkashi Bhala Ho Ashram Cottage(Happiness for All) None
Cabin in Kausani WFH-ready Cabin in Tea Estate Facing the Himalayas None
Home in Greater Noida Cute Hipster Boho Flat in Greater Noida None
Flat in Haridwar Prathna villa None
Cottage in Lansdowne Corbett Riverside Homestay None
Room in Kotabagh Syat House by the River, with forested mountains None
Place to stay in Lam Kande KeeKoo kanatal,Wealthinwhite None
Room in Harsil Harsil Heritage Homestay None
Room in Talwari Free Sample Stat Tridiva - A Himalayan Homestay None
Nature lodge in Ramnagar Tanhau, a sustainable boutique homestay None
Nature lodge in Ranikhet The Deodars: A charming colonial villa in Ranikhet ₹4,027
Room in Chakrata Bastiat Stays|A Rustic Getaway In Chakrata ₹3,993
Room in Narkand Aaramgah @ Cedar ₹6,847
Place to stay in Joshimath Dream Mountain Deluxe Room-3, Joshimath ₹2,739
Room in Dehradun Homestay in Dehradun: Pvt Room with 2 Double Bed ₹1,717
Place to stay in Faridabad Heritage Homes ₹1,278
Room in Gwalior Luxury stay+delicious homemade breakfast @phoolbag ₹1,426
Flat in Noida The WhiteRock - 41st Floor River view ₹5,466
Flat in New Delhi Cozy 2BHK Apt Next to Market in Gated Community ₹3,371
Room in New Delhi The Van Gogh House in Delhi ₹2,281
Flat in Noida Shades of Grey - 41 Floor River View Apartment ₹4,521
Flat in Noida Apartment(06)  by Serenity Homes in Noida ₹1,929
Apartment in Noida The Ivory Bliss - 35th Floor Studio Apartment ₹4,713
Flat in Greater Noida The Nova Nexus ₹3,503
Apartment in Noida Studio2 PvtEntrn Kitchn Balcny NoidaSec18Metro650m ₹1,291
Flat in Delhi Urban Oasis ₹5,706
Home in Noida Kudarat | Private plounge pool | couple friendly ₹4,272
Flat in Ghaziabad Cozy & Chic Your Perfect 1BHK ₹1,643
Guest house in Mussoorie Shadow Barn: Cuckoo Landour w/ Balcony+Valley View None
Flat in Noida Astley by Merakii—Your Next Favourite Memory! None
Flat in Greater Noida The Silver ClouDs None
Guest house in Mussoorie Shadow Barn: Barbet Landour w/ Balcony+Valley View None
Room in Noida ShortStay Standard None
Flat in Noida The Silver Stone | 31st Floor city lights view None
Apartment in Noida Studio1 PvtEntrn Kitchn Balcny NoidaSec18Metro650m None
Tiny home in Dehradun Devalsari Retreat
A Boutique Homestay None
Flat in Noida NOIDA ♥1BHK♥ 2F♥ Terrace♥ Parking Living Room♥♥ Wifi♥ Tv None
Flat in Reckong Peo Dhames Home : Your Home for Long-Term Stays None
Room in Kainchi Dham Shiva Peach Kainchi Dham None
Apartment in Rishikesh Aeviia by Merakii—Stay | Savor | Slay. None
Flat in Greater Noida Aesthetic Vibe 6 ( Private Suite ) None
Flat in Noida Hostie Asita 4-Studio Apt, Noida (No Parties) None
Apartment in Rishikesh Luxury Studio Apartment with Ganga View None
Campsite in Rishikesh Nature Camp on Neer waterfall,Neerville,Rishikesh. None
Apartment in Noida Boholuxe -41st floor | River facing None
Home in Noida Luxury Apartment -Jaypee Wishtown Noida (PRIVATE) None
Home in Noida Corner Villa Ground-Floor None
Cottage in Bhimtal SPRING LODGE..duplex None
Flat in Noida Swishh Stay (1rk) by Opulent Studio None
Flat in Noida Apartment (07) by Serenity Homes in Noida None
Flat in Noida The Midnight by DiMerro | 42nd Floor City View None
Flat in Noida Halcyon Haven By Genius Groves None
Guest house in Mussoorie Shadow Barn:Peafowl Landour w/ Balcony+Valley View None
Flat in Noida Green Giants 25 (1rk Studio) None
Apartment in Noida 42nd floor  Euphoria | River facing None
Apartment in Noida Studio1 PvtEntrn Kitchn Balcny NoidaSec18Metro650m None
Flat in Ghaziabad Aesthetic Vibe A (1rk studio at gaur mall) None
Apartment in Noida The Opulence Suite by DiMerro|41st Floor City View None
Flat in Noida 1BHK Luxury Studio Apartment by Serenity Homes None
Flat in Noida riveter studio@ 500 feet+private balcony + pool None
Guest suite in Noida Well presented studio with a beautiful garden None
Home in Noida Luxury Apartment -Jaypee Wishtown Noida (PRIVATE) None
Room in Noida House of Judah None
Flat in Greater Noida The Nivar Homes None
Bungalow in Dehradun Lal Kothi, Mountain Wrapped home w/Mughlai Cuisine None
Apartment in Greater Noida , Gautam Budh Nagar Condo with beautiful Golf view and near Expo Mart! None
Flat in Noida Halcyon Haven By Genius Groves None
Flat in Ghaziabad Aesthetic Vibe A (1rk studio at gaur mall) None
Apartment in Noida BluO Penthouse, BathTub, Terrace Garden#Staycation None
Flat in Noida A Chic and Cozy 2BHK Apartment with a City View None
Farm stay in Bhitar Wali Stargaze cosmic vibes None
Earthen home in IN Stoner's Creek None
Place to stay in Dhar Shulacha Pilaya Fayul Retreat (Kalpa)- India’s Highest Glamp Dome None
Room in Noida Noida Large Suite + en-suite (private Bathroom) None
Apartment in Rishikesh Ayur by Merakii—Serenity | Soul | Sanctuary. None
Place to stay in Bhowali, (MEALS iNCLUDED) Eat. Sleep. Repeat @ Skylit Hut 1 None
Nature lodge in Rishikesh RishisInternational Rishikesh- Retreat Into Nature None
Home in Nainital Naini Lakefront homestay None
Apartment in Noida The Opulence Suite by DiMerro|41st Floor City View None
Flat in Vrindavan 𝐊𝗋𝗂𝗌ɦ𐓣 𝗄υ𐓣𝗃 -  Spritual stay in Vrindavan None
Room in Fagu OCB Stays:Stargazing Cabin None
Guest house in Mussoorie Shadow Barn: Treeswift Landour w/ Balcony+View None
Flat in Delhi Homlee-Best Value flat with kitchen Near Metro None
Hotel in Greater Noida Amaltaash by sandane homes greater noida None
Flat in Noida Apartment (07) by Serenity Homes in Noida None
Flat in Vrindavan 𝐊𝗋𝗂𝗌ɦ𐓣 𝗄υ𐓣𝗃 -  Spritual stay in Vrindavan None
Flat in Noida A Chic and Cozy 2BHK Apartment with a City View None
Room in Fagu OCB Stays:Stargazing Cabin None
Room in Noida House of Judah None
Hotel in Agra Decent Room in Boutique Hotel, ½ km from Taj Mahal None
Cottage in Bhimtal SPRING LODGE..duplex None
Flat in Girdharpur Sunarasi Opulent Suite 16 (Galaxy Blue Sapphire Mall Noida) None
Boutique hotel in Agra Queen Double Room/200 Mtrs from Tajmahal Parking None
Apartment in Vrindavan Vasudev Kutumb: Atithi devo bava None
Room in Greater Noida Single Room @ Rudravas( a unit of BonKala ) None
Flat in Noida Studio Apartment by Serenity Homes in Noida None
Room in Rishikesh Shankar-Bhawan Stay None
Apartment in Greater Noida , Gautam Budh Nagar Condo with beautiful Golf view and near Expo Mart! None
Flat in Vrindavan Manmohana: Our blissful Krishna abode in Vrindavan None
Shared room in Bhowali (MEALS iNCLUDED) Work from hills @ Unisex  Dorm 1 None
Flat in Ithaira CityScape Studio by Opulent ₹1,600
Guest house in Mussoorie Shadow Barn: Treeswift Landour w/ Balcony+View ₹4,565
Place to stay in Noida Independent apartment with a garden in city centre ₹2,394
Apartment in Noida Luxurious Home with Terrace Garden: Bougainvillea ₹11,362
Apartment in Noida Hues of Blues - Luxe Stay
(Entire Luxury Studio) ₹4,200
Room in Noida, Gautam Buddha Nagar Cozy Bungalow w/ Large Terrace, Serene House ₹1,910
Room in Noida O-Space ₹1,716
Tiny home in Dehradun Devalsari Retreat
A Boutique Homestay ₹1,601
Flat in Noida Grehshobha's Humble Abode ₹2,057
Flat in Noida AmigosStay High rise studio with river view. ₹3,090
Apartment in Noida Scenes. ₹3,652
Flat in Ithaira Palm stay [1RK Studio self checkin] ₹1,703
Apartment in Noida Nivasa: Luxury Apartment Stay by JP Homestays ₹2,111
Apartment in Noida Smart TV & Sunset Views | Your Ideal Stay ₹3,635
Apartment in Rishikesh Luxury Studio Apartment with Ganga View ₹5,135
Cottage in Mussoorie Brisa Cottage - Discover Nature and Yourself ₹11,069
Boutique hotel in Agra Queen Double Room/200 Mtrs from Tajmahal Parking ₹1,349
Flat in Noida Private Peaceful Hideaway Escape ₹1,722
Flat in Mussoorie Herne Lodge 8 - Cliff View ₹4,882
Apartment in Vrindavan Vrunda 2bhk spacious and cozy Homestay ₹4,796
Apartment in Noida Luxury Riverfacing apartment with a skyline view ₹4,428
Boutique hotel in Agra room with balcony near Taj@ Anukampa guest house ₹2,100
Flat in Suwakholi Panoramic Jacuzzi Suite with huge Balcony & Swing ₹7,762
Room in Ghaziabad Bright Loft in Heart of Downtown ₹1,826
Farm stay in Bhitar Wali Stargaze cosmic vibes ₹9,028
Home in Agra Hey Gram! ₹4,222
Guest house in Rishikesh Green Valley Cottage (standard room) ₹1,848
Apartment in Vrindavan Vrindavan Skyline Apartment 1BHK : Sunset view ₹2,798
Room in Noida Cosy Room In Central Noida ₹2,282
Apartment in Noida Sage Luxe Retreat | Luxury Studio Apartment ₹2,244
Treehouse in Mussoorie Srivasa - Misty Pine Cottage, Mussoorie ₹5,934
Room in Rishikesh Yogsadhak Homestay Experience ₹1,190
Apartment in Sukha Northern Homes ₹5,597
Room in Mussoorie Heaven by The Kiana's ₹9,649
Boutique hotel in Agra Private Deluxe Balcony Room- 1.6 km from Tajmahal ₹1,232
Home in Nainital Naini Lakefront homestay ₹4,000
Flat in Noida Supernova Spira Studio -High Flr Awesome RiverView None
Guest suite in Dehradun Laid back Homestay in Dalanwala None
Room in Noida Cosy Room In Central Noida None
Room in Rishikesh Luxury apartment overlooking Ganges Balcony Room None
Flat in Ghaziabad Homlee - Villa Apartment In Ghaziabad/east del None
Villa in Dehradun Picturesque Pahadi Villa in Dehradun None
Home in Noida JEWEL OF THE EAST - Fully Furnished Luxury Apartmt None
Apartment in Nainital Colonial House With a  Garden l Mystic Abode None
Cottage in Nainital Bir Terraces : Utopia in the hills! None
Room in Noida Jaypee Klassic Wishtown quiet, light, windy, green None
Apartment in Rishikesh Ferye by Merakii—Serene | Scenic | Soulful. None
Room in Ghaziabad Kutum Bari at Vaishali Hosted by Susamoy None
Flat in Noida The Boho essence | 31st Floor River View Apartment None
Apartment in Greater Noida The Sky in (18th floor 1RK Private Studio) None
Farm stay in Khuranwa Private farm-stay near Dehradun city centre None
Nature lodge in Nainital Garden Hut None
Apartment in Dehradun Serenity by Shreya Homez near Mussorie & Rajpur rd None
Apartment in Noida The Sun Spaces None
Room in Noida Cosy Room In Central Noida None
Apartment in Noida The Blush by DiMerro |40th Floor City & River View None
Place to stay in Bhowali, (MEALS iNCLUDED) Eat. Sleep. Repeat @ Skylit Hut 1 None
Room in Dehradun Budget Room wd Shared Washroom - Himalay Homestays None
Room in Ghaziabad Kutum Bari at Vaishali Hosted by Susamoy None
Earthen home in IN Stoner's Creek None
Flat in Vrindavan 𝐊𝗋𝗂𝗌ɦ𐓣 𝗄υ𐓣𝗃 -  Spritual stay in Vrindavan None
Tiny home in Siloti Pant Gadeni Stays : Sky cabin at Naukuchiatal None
Flat in Noida Sky High Panoramic City View None
Flat in Noida Wine Door by NobleHomes None
Flat in Ghaziabad Sojourn Stay- Ultra Luxury Condo None
Apartment in Vrindavan Krishnam Kunj- Heritage House None
Flat in Ithaira Skylight (Private 1BHK top floor) None
Cottage in Bhimtal Whistling Thrush Cottage, Bhimtal (2bhk) None
Apartment in Noida Best 5 Star Luxury River View Room in SuperNova None
Apartment in Noida Studio in the Clouds 42nd Floor, City & River View None
Room in Delhi Pvt Room for Females apartment,5 min walk to metro None
Place to stay in Noida Japanese Business Hotel! Noida Sec 63, EC Metro None
Flat in Mussoorie Herne Lodge 4 - A Mountain Home Away From Home! ₹3,058
Room in Rishikesh Yogsadhak's Peaceful Abode ₹1,098
Home in Vrindavan Vraj ₹1,700
Boutique hotel in Mussoorie The Hill Story -"Serenity Nest" ₹2,231
Apartment in Vrindavan Harikunj: Blissful Krishna abode ₹2,396
Room in Nainital Ejaa Homestay- Walnut Cottage ₹1,900
Flat in Ghaziabad Sojourn Stay- Ultra Luxury Condo ₹3,787
Guest house in Rishikesh Ganga kinare room with  private balcony ₹3,810
Flat in Girdharpur Sunarasi Opulent Suite (Studio at galaxy blue sapphire) ₹2,913
Tiny home in Sanguri Gaon Gadeni stays : A-frame cabin at Naukuchiatal ₹4,565
Apartment in Noida 42nd floor  Euphoria | River facing ₹4,573
Apartment in Noida Le-Royale -42nd floor, Luxury Studio with lakeview ₹4,816
Boutique hotel in Agra room with balcony near Taj@ Anukampa guest house ₹2,100
Home in Haridwar Ganga View Retreat -Just Steps Away from Ganga ₹2,278
Flat in Noida Oriison ~ Your blissful studio! ₹3,941
Hostel in Sangla Zostel Sangla | Deluxe Room ₹2,419
Tiny home in Sanguri Gaon Gadeni Stays - Glamping Dome at Naukuchiatal ₹4,565
Place to stay in Dhanolti #MiddleOfNowhere Stays, Dhanaulti ( Mud House ) ₹4,451
Apartment in Dehradun Beautiful Studio apartment - Himalay Homestays None
Cottage in Nainital Bir Terraces : Utopia in the hills! None
Guest house in Govardhan mud house rooms None
Room in Nainital Ejaa Homestay- Walnut Cottage None
Room in Dehradun Big Room with Shared Washroom- Himalay Homestays None
Apartment in Allhepur Vrindavan 1-Bed Room Entire Apartment Stay None
Flat in Noida Halcyon Haven By Genius Groves None
Flat in Chhatikara Studio "Cozy, well-lit and warm" None
Apartment in Ghaziabad Stylish Private Modern 2-Bedroom Retreat Delhi NCR None
Cottage in Mussoorie The Hawk’s Nest at Firs Estate None
Room in Agra Spacious Bed & Breakfast near Taj Mahal None
Room in Mussoorie Stargaze Vibes farm None
Townhouse in Mussoorie One Oak Maryville None
Home in Dehradun Nature’s Cove Magnolia None
Apartment in Ghaziabad Super Luxury Studio Apartment Cabana None
Home in Noida JEWEL OF THE EAST - Fully Furnished Luxury Apartmt None
Guest suite in Mussorrie  The Eagle’s Nest at Firs Estate None
Home in Dharali Duplexes  - Harshil (Dharali) None
Nature lodge in Ramnagar Tanhau, a sustainable boutique homestay None
Apartment in Ghaziabad Premium Suite - Couple Friendly- For Elite class None
Farm stay in Kotgarh Phalbagh Stay None
Chalet in Kausani Rays Himalayan  Snow view Luxurious  Cottage None
Bungalow in Dehradun Serene Sanctuary None
Apartment in Agra Taj Vibes by Vibz None
Apartment in Rishikesh Ferye by Merakii—Serene | Scenic | Soulful. None
Flat in Sector 94 Noida The Pebble Stone - City Lights View None
Apartment in Vrindavan Vrinda Vihar| Studio 1| Parking | kitchen| Balcony None
Flat in Noida The Boho essence | 31st Floor River View Apartment None
Room in Chakrata Bastiat Stays|A Rustic Getaway In Chakrata None
Flat in Dehradun "The Gray-Den" near Rajpur Rd. None
Flat in Ghaziabad Sojourn Stay- Ultra Luxury Condo None
Nature lodge in Kotabagh Sunrise room- bright & airy with many open spaces None
Room in Harinagar Chanddeva Shanti Kunjj: Lake View Cottage Bhimtal None
Flat in Noida Noida, Sec 14, 3BHK, First Flr, Brkfast, Caretaker None
Apartment in Noida The Sun Spaces None
Guest suite in Dehradun Laidback Outhouse Homestay in Dalanwala None
Flat in Vrindavan The Royal Indian Odyssey - Majestic Luxury Suite None
Flat in Noida Modern 2Bhk Designed for Comfort, Soulful Appt 102 None
Flat in Ghaziabad Homlee-Vasundhara-2 3BHK Flat wth kitchen &parking None
Place to stay in Noida Serene - 1 Master Bedroom in a Bungalow None
Flat in Noida Sky High Riverfront Gateway by Genius Groves None
Flat in Ghaziabad Luxury Bright & Airy Apartment None
Boutique hotel in Agra Private Deluxe Balcony Room- 1.6 km from Tajmahal None
Flat in Ghaziabad Homlee-Gokul 3BHK Flat-Lift-Parking-vaishali metro None
Home in Vrindavan 2 km from Prem Mandir # 3 BHK None
Room in Dehradun Adidev Homestay None
Guest suite in Rishikesh Room w kitchen+WC near AIIMS, FREE Breakfast+ Wifi None
Apartment in Noida My House Your House - Sector 50 Noida None
Place to stay in Agra Luxurious Studio in DayalBagh Agra None
Flat in Chhatikara Studio "Cozy, well-lit and warm" None
Apartment in Noida Best 5 Star Luxury River View Room in SuperNova None
Room in Delhi Pvt Room for Females apartment,5 min walk to metro None
Apartment in Noida Mi Casa Tu Casa Studio Apartment - Sector 76, Noida None
Apartment in Faridabad 3 BHK Apartment (Accommodate upto 9 guests) None
Tiny home in Sanguri Gaon Gadeni stays : A-frame cabin at Naukuchiatal ₹3,994
Hotel in Greater Noida Amaltaash by sandane homes greater noida ₹1,680
Villa in Raiwala Neelkanth Villa Homestay ₹4,565
Flat in Noida Hostie Kalini-Yamuna view Apartment (No Parties) ₹7,018
Apartment in Ghaziabad Gitanjali Homestay | 2BHK Independent Floor Apt. ₹3,765
Flat in Noida Private Elegante Luxury Stay | 21thFloor ₹1,722
Room in Noida Homely Cozy Room ₹1,712
Flat in Dehradun Studio Apartment on ground floor-Himalay Homestays ₹1,039
Cabin in Mussoorie Fern Villas Cabin 1, Landour. (Near Bakehouse) ₹9,129
Flat in Rajpur Khadar Plush 1bhk @Vrinda Stays| 2 beds ₹2,099
Apartment in Vrindavan Vrunda 2bhk spacious and cozy Homestay ₹4,796
Apartment in Fuleta Tadaima “ 2 BHK Luxury Apartment “ ₹3,994
Flat in Vrindavan Shyam Rang Palace - next to Iskcon & prem mandir ₹3,424
Room in Dehradun Budget Room wd Shared Washroom - Himalay Homestays ₹595
Flat in Noida Luxurious suite 06 by Opulent Studio ₹2,742
Cottage in Mussoorie The Monal - Private Cottage by "The Skydrift" ₹5,991
Flat in Faridabad Ayush’s Home ₹2,856
Treehouse in Landour The Landour Cottage ~ Forest Treehouse ₹9,144

In [170]:
datafr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 270 entries, 0 to 269
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         270 non-null    object
 1   Description  270 non-null    object
 2   Price        90 non-null     object
dtypes: object(3)
memory usage: 8.4+ KB