In [1]:
import pandas as pd 
import numpy as np 
data = pd.read_csv('D:\Python_Code\Project_DS108\ds108\Data_clean\Final_Data_ver2.csv')

data.columns

Index(['Unnamed: 0', 'Age', 'Height', 'National', 'TotAD', 'WonAD', 'LostAD',
       'CrAss', 'CorAss', 'ThrbAss', 'FreAss', 'ThrInAss', 'OthAss', 'TotAss',
       'BlkSh', 'BlkCr', 'BlkPs', 'YelC', 'RedC', 'TotClr', 'UnDrib',
       'SucDrib', 'TotDrib', 'Fouled', 'Fouls', 'TotGs', 'SYBGs', 'PAGs',
       'OOBGs', 'TotInt', 'TotKPs', 'LKPs', 'SKPs', 'COF', 'TotPs', 'AccLB',
       'InAccLB', 'AccSP', 'InAccSP', 'UnTch', 'Dispo', 'TotSav', 'SYBSav',
       'PASav', 'OOBSav', 'TotSh', 'OOBSh', 'SYBSh', 'PASh', 'TotTkl',
       'DribPast', 'TotAttTkl', 'Player', 'Mins', 'Goals', 'Assists', 'Yel',
       'Red', 'SpG', 'PS%', 'AerialsWon', 'MotM', 'Rating', 'League', 'CLB',
       'Main_position', 'Foot', 'Market_Value', 'Months_left', 'Start_app',
       'Sub_app'],
      dtype='object')

In [2]:
col_chosen = ['Player','Start_app', 'Sub_app' , 'League', 'CLB', 'Age', 'Height', 'National', 'Mins', 'Goals', 'Assists','SpG', 'PS%', 'AerialsWon', 'MotM', 'Rating', 'Main_position', 'Foot', 'Months_left', 'Market_Value']

data_bi = data[col_chosen]
data_bi

,Player,Start_app,Sub_app,League,CLB,Age,Height,National,Mins,Goals,Assists,SpG,PS%,AerialsWon,MotM,Rating,Main_position,Foot,Months_left,Market_Value
0,Adam Hlozek,19.0,5.0,Bundesliga,TSG 1899 Hoffenheim,22.0,188.0,Czech Republic,1619.0,7.0,2.0,2.2,70.4,1.5,3.0,6.84,Second Striker,right,49.0,18000000.0
1,Adrian Beck,15.0,14.0,Bundesliga,1.FC Heidenheim 1846,27.0,186.0,Germany,1383.0,2.0,1.0,1.1,81.9,0.9,0.0,6.55,Attacking Midfield,right,37.0,2000000.0
2,Alassane Plea,23.0,5.0,Bundesliga,Borussia Mönchengladbach,32.0,181.0,France,1812.0,11.0,4.0,1.4,75.6,0.5,2.0,6.76,Centre-Forward,right,13.0,6000000.0
3,Aleix Garcia,15.0,10.0,Bundesliga,Bayer 04 Leverkusen,27.0,173.0,Spain,1295.0,3.0,3.0,0.6,91.0,0.1,1.0,6.68,Central Midfield,right,49.0,20000000.0
4,Aleksandar Pavlovic,16.0,2.0,Bundesliga,Bayern Munich,20.0,188.0,Germany,1250.0,1.0,0.0,0.4,94.1,0.5,0.0,6.85,Defensive Midfield,both,49.0,50000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2244,Nicolas Gonzalez,19.0,3.0,SerieA,Juventus FC,27.0,180.0,Argentina,1471.0,2.0,2.0,1.7,76.6,2.4,0.0,6.81,Right Winger,left,1.0,28000000.0
2245,Tasos Douvikas,3.0,6.0,SerieA,Como 1907,25.0,186.0,Greece,369.0,2.0,0.0,1.0,77.3,0.7,0.0,6.39,Centre-Forward,right,49.0,8000000.0
2246,Thorir Helgason,11.0,6.0,SerieA,US Lecce,24.0,187.0,Iceland,946.0,0.0,4.0,0.8,71.8,0.9,0.0,6.49,Central Midfield,right,13.0,2500000.0
2247,Valentin Castellanos,24.0,1.0,SerieA,SS Lazio,26.0,178.0,Argentina,2036.0,10.0,3.0,3.7,69.9,2.4,4.0,7.08,Centre-Forward,right,37.0,25000000.0
2248,Vanja Vlahovic,0.0,3.0,SerieA,Juventus FC,21.0,190.0,Serbia,58.0,0.0,0.0,0.3,66.7,0.0,0.0,6.14,Centre-Forward,left,13.0,45000000.0

In [3]:
data_bi['National'].unique()

array(['Czech Republic', 'Germany', 'France', 'Spain', 'Sweden',
       'Austria', 'Canada', 'Mali', 'Belgium', 'Morocco', 'Norway',
       'Denmark', 'Serbia', 'Croatia', 'Portugal', 'Eritrea',
       'Burkina Faso', 'Switzerland', 'Slovenia', 'Brazil', 'Georgia',
       'Turkey', 'England', 'Costa Rica', 'Netherlands', 'Israel',
       'Slovakia', 'Tunisia', 'Argentina', 'Bosnia-Herzegovina', 'Italy',
       'Algeria', 'Kosovo', 'Nigeria', 'Finland', 'USA', 'Japan',
       'South Korea', 'Ukraine', 'Poland', 'Estonia', 'Greece', 'Guinea',
       'Scotland', 'Ecuador', 'Hungary', 'Sierra Leone', 'Benin',
       'Uzbekistan', 'Ivory Coast', 'Cameroon', 'Ghana', 'Albania',
       'Wales', 'Jamaica', 'Australia', 'Ireland', 'New Zealand',
       'N. Ireland', 'Colombia', 'Uruguay', 'Mexico', 'Senegal',
       'Paraguay', 'Zimbabwe', 'Egypt', 'Zambia', 'Romania', 'Gambia',
       'DR Congo', 'Iceland', 'Russia', 'Macedonia', 'Venezuela',
       'Equatorial Guinea', 'Dominican Rep.', 'Peru', 'Panama', 'Haiti',
       'Angola', 'Chile', 'Central African Rep.', 'Gabon', 'Kenya',
       'Guadeloupe', 'Guinea-Bissau', 'Malta', 'Burundi', 'Libya',
       'U.A.E.', 'Montenegro', 'Congo', 'Cyprus', 'Lithuania', 'Armenia',
       'Iran', 'Saudi Arabia'], dtype=object)

In [4]:
# Map quốc gia -> châu lục
country_to_continent = {
    "Europe": ["Albania", "Armenia", "Austria", "Belgium", "Bosnia-Herzegovina", "Croatia", "Cyprus", "Czech Republic", "Denmark", "England", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Lithuania", "Macedonia", "Malta", "Montenegro", "Netherlands", "N. Ireland", "Norway", "Poland", "Portugal", "Romania", "Russia", "Scotland", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "Wales"],
    "Africa": ["Algeria", "Angola", "Benin", "Burkina Faso", "Burundi", "Cameroon", "Central African Rep.", "Congo", "DR Congo", "Egypt", "Equatorial Guinea", "Eritrea", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau", "Ivory Coast", "Kenya", "Libya", "Mali", "Morocco", "Nigeria", "Senegal", "Sierra Leone", "Tunisia", "Zambia", "Zimbabwe"],
    "Asia": ["Georgia", "Iran", "Israel", "Japan", "Saudi Arabia", "South Korea", "Turkey", "U.A.E.", "Uzbekistan"],
    "Americas": ["Argentina", "Brazil", "Canada", "Chile", "Colombia", "Costa Rica", "Dominican Rep.", "Ecuador", "Haiti", "Jamaica", "Mexico", "Panama", "Paraguay", "Peru", "USA", "Uruguay", "Venezuela", "Guadeloupe"],
    "Oceania": ["Australia", "New Zealand"]

}
# Đảo ngược dictionary: từ quốc gia → châu lục
flat_country_to_continent = {
    country: continent 
    for continent, countries in country_to_continent.items() 
    for country in countries
}

# Map từng quốc gia trong cột 'National' sang châu lục
data_bi['Continent'] = data_bi['National'].map(flat_country_to_continent)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_25232\633953102.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bi['Continent'] = data_bi['National'].map(flat_country_to_continent)

In [5]:
data_bi['Continent'].unique()

array(['Europe', 'Americas', 'Africa', 'Asia', 'Oceania'], dtype=object)

In [6]:
# Nhóm thủ môn + hậu vệ (phòng ngự)
group_defense = ['Goalkeeper', 'Centre-Back', 'Left-Back', 'Right-Back']

# Nhóm tiền vệ 
group_midfield = ['Defensive Midfield', 'Central Midfield', 'Left Midfield', 'Right Midfield']

# Nhóm tiền đạo 
group_attack = ['Centre-Forward', 'Second Striker', 'Attacking Midfield', 'Left Winger', 'Right Winger']

def map_position(pos):
    if pos in group_defense:
        return 'Phòng ngự'
    elif pos in group_midfield:
        return 'Tiền vệ'
    elif pos in group_attack:
        return 'Tiền đạo'
    else:
        return 'Khác'
data_bi['Position_Group'] = data_bi['Main_position'].apply(map_position)
#data_bi = data_bi.drop(columns= 'Main_position')

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_25232\1483450610.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bi['Position_Group'] = data_bi['Main_position'].apply(map_position)

In [7]:
data_bi

,Player,Start_app,Sub_app,League,CLB,Age,Height,National,Mins,Goals,...,PS%,AerialsWon,MotM,Rating,Main_position,Foot,Months_left,Market_Value,Continent,Position_Group
0,Adam Hlozek,19.0,5.0,Bundesliga,TSG 1899 Hoffenheim,22.0,188.0,Czech Republic,1619.0,7.0,...,70.4,1.5,3.0,6.84,Second Striker,right,49.0,18000000.0,Europe,Tiền đạo
1,Adrian Beck,15.0,14.0,Bundesliga,1.FC Heidenheim 1846,27.0,186.0,Germany,1383.0,2.0,...,81.9,0.9,0.0,6.55,Attacking Midfield,right,37.0,2000000.0,Europe,Tiền đạo
2,Alassane Plea,23.0,5.0,Bundesliga,Borussia Mönchengladbach,32.0,181.0,France,1812.0,11.0,...,75.6,0.5,2.0,6.76,Centre-Forward,right,13.0,6000000.0,Europe,Tiền đạo
3,Aleix Garcia,15.0,10.0,Bundesliga,Bayer 04 Leverkusen,27.0,173.0,Spain,1295.0,3.0,...,91.0,0.1,1.0,6.68,Central Midfield,right,49.0,20000000.0,Europe,Tiền vệ
4,Aleksandar Pavlovic,16.0,2.0,Bundesliga,Bayern Munich,20.0,188.0,Germany,1250.0,1.0,...,94.1,0.5,0.0,6.85,Defensive Midfield,both,49.0,50000000.0,Europe,Tiền vệ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2244,Nicolas Gonzalez,19.0,3.0,SerieA,Juventus FC,27.0,180.0,Argentina,1471.0,2.0,...,76.6,2.4,0.0,6.81,Right Winger,left,1.0,28000000.0,Americas,Tiền đạo
2245,Tasos Douvikas,3.0,6.0,SerieA,Como 1907,25.0,186.0,Greece,369.0,2.0,...,77.3,0.7,0.0,6.39,Centre-Forward,right,49.0,8000000.0,Europe,Tiền đạo
2246,Thorir Helgason,11.0,6.0,SerieA,US Lecce,24.0,187.0,Iceland,946.0,0.0,...,71.8,0.9,0.0,6.49,Central Midfield,right,13.0,2500000.0,Europe,Tiền vệ
2247,Valentin Castellanos,24.0,1.0,SerieA,SS Lazio,26.0,178.0,Argentina,2036.0,10.0,...,69.9,2.4,4.0,7.08,Centre-Forward,right,37.0,25000000.0,Americas,Tiền đạo
2248,Vanja Vlahovic,0.0,3.0,SerieA,Juventus FC,21.0,190.0,Serbia,58.0,0.0,...,66.7,0.0,0.0,6.14,Centre-Forward,left,13.0,45000000.0,Europe,Tiền đạo

In [8]:
data_bi.columns

Index(['Player', 'Start_app', 'Sub_app', 'League', 'CLB', 'Age', 'Height',
       'National', 'Mins', 'Goals', 'Assists', 'SpG', 'PS%', 'AerialsWon',
       'MotM', 'Rating', 'Main_position', 'Foot', 'Months_left',
       'Market_Value', 'Continent', 'Position_Group'],
      dtype='object')

In [9]:
# Goals_per_Min = SUM('Table'[Goals]) / SUM('Table'[Mins]).
data_bi['Apps'] = data_bi['Start_app'] + data_bi['Sub_app']
data_bi['Goals_per_app'] = data_bi['Goals'] / data_bi['Apps']

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_25232\853103537.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bi['Apps'] = data_bi['Start_app'] + data_bi['Sub_app']
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_25232\853103537.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_bi['Goals_per_app'] = data_bi['Goals'] / data_bi['Apps']

In [10]:
data_bi.to_csv('D:\Power_BI\data_bi.csv')