In [1]:
import pandas as pd
import numpy as np
from unidecode import unidecode

In [2]:


# Danh sách các file CSV
filenames = [
    "base_info_Bundesliga.csv",
    "data_details_Aerial_Bundesliga.csv",
    "data_details_Assists_Bundesliga.csv",
    "data_details_Blocks_Bundesliga.csv",
    "data_details_Cards_Bundesliga.csv",
    "data_details_Clearances_Bundesliga.csv",
    "data_details_Dribbles_Bundesliga.csv",
    "data_details_Fouls_Bundesliga.csv",
    "data_details_Goals_Bundesliga.csv",
    "data_details_Interception_Bundesliga.csv",
    "data_details_Key passes_Bundesliga.csv",
    "data_details_Offsides_Bundesliga.csv",
    "data_details_Passes_Bundesliga.csv",
    "data_details_Possession loss_Bundesliga.csv",
    "data_details_Saves_Bundesliga.csv",
    "data_details_Shots_Bundesliga.csv",
    "data_details_Tackles_Bundesliga.csv",
    "data_summary_Bundesliga.csv"
]

#for file in filenames:
    


# Đọc tất cả các file vào một danh sách DataFrame
df_list = [pd.read_csv(file) for file in filenames]

# Nối các DataFrame theo cột (ngang)
data = pd.concat(df_list, axis=1)

# Hiển thị kết quả
data

,Unnamed: 0,Name,Club,Age,Height,National,Positions,Unnamed: 0.1,Unnamed: 0,ToTAD,...,Mins,Goals,Assists,Yel,Red,SpG,PS%,AerialsWon,MotM,Rating
0,0,Omar Marmoush,Manchester City,26 years old (07-02-1999),183cm,Egypt,"Attacking Midfielder (Centre, Left), Forward",0,0,1.2,...,1454,15,9,2,-,4.5,79.6,0.4,9,8.23
1,1,Harry Kane,Bayern Munich,31 years old (28-07-1993),188cm,England,"Attacking Midfielder (Centre), Forward",1,1,1.6,...,2272,24,7,5,-,3.7,80.4,1,9,7.71
2,2,Michael Olise,Bayern Munich,23 years old (12-12-2001),184cm,France,"Attacking Midfielder (Centre, Left, Right)",2,2,0.6,...,2078,9,12,2,-,2.4,86.4,0.3,6,7.61
3,3,Jamal Musiala,Bayern Munich,22 years old (26-02-2003),184cm,Germany,"Midfielder (Centre, Left, Right)",3,3,0.8,...,1807,12,2,3,-,2.7,83.5,0.3,5,7.56
4,4,Florian Wirtz,Bayer Leverkusen,21 years old (03-05-2003),176cm,Germany,"Attacking Midfielder (Centre, Left, Right), Fo...",4,4,1.5,...,2087,9,10,2,-,2.4,82.6,0.3,7,7.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,482,Grant-Leon Ranos,Kaiserslautern,21 years old (20-07-2003),180cm,NaN,Forward,482,482,0.5,...,18,-,-,1,-,-,63.6,-,-,5.89
483,483,Daniel Peretz,Bayern Munich,24 years old (10-07-2000),195cm,Israel,Goalkeeper,483,483,-,...,270,-,-,1,-,-,75.5,-,-,5.88
484,484,Norman Theuerkauf,FC Heidenheim,38 years old (24-01-1987),183cm,Germany,"Defender (Centre, Left), Defensive Midfielder (C)",484,484,-,...,21,-,-,-,-,1,83.3,-,-,5.87
485,485,Maximilian Philipp,Freiburg,31 years old (01-03-1994),183cm,Germany,"Attacking Midfielder (Centre, Left, Right), Fo...",485,485,1,...,15,-,-,-,-,0.5,42.9,-,-,5.85
486,486,Ivan Nekic,Holstein Kiel,24 years old (24-12-2000),184cm,Croatia,Defender,486,486,-,...,72,-,-,-,-,-,75,-,-,5.33

In [3]:

data= data.drop(columns= ['Unnamed: 0', 'Name'])
data['League'] = 'Bundesliga'

In [4]:
count_club = data['Club'].value_counts()
count_club

Club
Hoffenheim              30
RB Leipzig              27
Bayern Munich           27
St. Pauli               27
VfB Stuttgart           26
Augsburg                26
Holstein Kiel           26
Eintracht Frankfurt     25
FC Heidenheim           25
Union Berlin            25
Borussia Dortmund       25
Borussia M.Gladbach     25
Freiburg                24
Wolfsburg               24
Werder Bremen           23
Bayer Leverkusen        23
Mainz 05                23
Bochum                  23
Kaiserslautern           3
Borussia Dortmund II     3
Real Valladolid          2
Salzburg                 2
Manchester City          1
Al Nassr FC              1
Plymouth                 1
Fiorentina               1
Aston Villa              1
Reims                    1
Rennes                   1
Tottenham                1
Torino                   1
Galatasaray              1
Karlsruher SC            1
Fortuna Duesseldorf      1
Schalke 04               1
Royal Antwerp            1
FC St. Gallen            1
Celtic                   1
Sevilla                  1
Nuernberg                1
FC Lausanne-Sport        1
Lazio                    1
Debrecen                 1
VfB Stuttgart II         1
AEL Limassol             1
Name: count, dtype: int64

In [5]:
data = data[data['Club'].isin(count_club[count_club > 20].index)]

In [6]:
data['Club'].value_counts()

Club
Hoffenheim             30
Bayern Munich          27
St. Pauli              27
RB Leipzig             27
Augsburg               26
VfB Stuttgart          26
Holstein Kiel          26
FC Heidenheim          25
Borussia M.Gladbach    25
Eintracht Frankfurt    25
Borussia Dortmund      25
Union Berlin           25
Freiburg               24
Wolfsburg              24
Bayer Leverkusen       23
Mainz 05               23
Werder Bremen          23
Bochum                 23
Name: count, dtype: int64

In [7]:
player_count = data['Player'].value_counts()
player_count

Player
Niklas Dorsch         2
Salih Özcan           2
Frans Krätzig         2
Jacob Bruun Larsen    2
Mërgim Berisha        2
                     ..
Hennes Behrens        1
Mario Hermoso         1
Leonidas Stergiou     1
Ivan Ordets           1
Robert Andrich        1
Name: count, Length: 443, dtype: int64

In [8]:
invalid_player = data[data.duplicated(subset='Player', keep=False)]


for p in invalid_player['Player'].unique():
    
    players = data[data['Player'] == p]
    
    # Tìm phần tử có số phút thi đấu Mins lớn nhất
    player_to_keep = players.loc[players['Mins'].idxmax()]
    
    # Xóa các phần tử còn lại
    data = data.drop(players[players.index != player_to_keep.name].index)

In [9]:
data['Player'].value_counts()

Player
Ivan Nekic                1
Harry Kane                1
Michael Olise             1
Jamal Musiala             1
Florian Wirtz             1
                         ..
Ritsu Doan                1
Nathaniel Brown           1
Franck Honorat            1
Maximilian Mittelstädt    1
Nadiem Amiri              1
Name: count, Length: 443, dtype: int64

In [10]:
data[data['Player'] == 'Niklas Dorsch']

,Club,Age,Height,National,Positions,Unnamed: 0.1,ToTAD,WonAD,LostAD,CrAss,...,Goals,Assists,Yel,Red,SpG,PS%,AerialsWon,MotM,Rating,League
252,FC Heidenheim,27 years old (15-01-1998),178cm,Germany,Midfielder (Centre),252,0.9,0.4,0.5,-,...,2,2,5,1,0.4,85.3,0.4,-,6.47,Bundesliga

In [11]:
data.head(1)

,Club,Age,Height,National,Positions,Unnamed: 0.1,ToTAD,WonAD,LostAD,CrAss,...,Goals,Assists,Yel,Red,SpG,PS%,AerialsWon,MotM,Rating,League
1,Bayern Munich,31 years old (28-07-1993),188cm,England,"Attacking Midfielder (Centre), Forward",1,1.6,1,0.7,-,...,24,7,5,-,3.7,80.4,1,9,7.71,Bundesliga

In [12]:
data['Club'].unique()

array(['Bayern Munich', 'Bayer Leverkusen', 'Eintracht Frankfurt',
       'Borussia M.Gladbach', 'RB Leipzig', 'Wolfsburg',
       'Borussia Dortmund', 'Mainz 05', 'VfB Stuttgart', 'Freiburg',
       'Hoffenheim', 'Augsburg', 'Union Berlin', 'Werder Bremen',
       'FC Heidenheim', 'St. Pauli', 'Holstein Kiel', 'Bochum'],
      dtype=object)

In [13]:
data_info = data.sort_values(by = 'Player', ascending= True)
data_value = pd.read_csv('/home/xuanhoang/Desktop/Working/0498342198341420/Python_Code/Project_DS108/ds108/Transfermark /Bundesliga/Bundesliga_Value.csv')
data_info.shape

(443, 67)

In [14]:
#data_value['Name'] = data_value['Name'].apply(unidecode)
#data_info['Player'] = data_info['Player'].apply(unidecode)
# Bỏ dấu, chuyển chữ thường và loại dấu gạch nối
data_value['Name'] = data_value['Name'].apply(lambda x: unidecode(x).lower().replace("-", " "))
# Bỏ dấu, chuyển chữ thường và thay dấu gạch nối bằng dấu cách
data_info['Player'] = data_info['Player'].apply(lambda x: unidecode(x).lower().replace("-", " "))

In [15]:
merged_rows = []
name_not_found = []
not_found_indices = []

for i in range(len(data_info)):
    flag = 0
    for j in range(len(data_value)):
        if data_info.iloc[i]['Player'] == data_value.iloc[j]['Name']:
            # Nối 2 hàng lại theo chiều ngang
            merged = pd.concat([
                data_info.iloc[i],
                data_value.iloc[j].drop('Name')  # bỏ cột trùng
            ])
            merged_rows.append(merged)

            flag = 1
            break
    if flag == 0:
        print('Index = ', i, 'Not Found : ', data_info.iloc[i]['Player'])
        name_not_found.append(data_info.iloc[i]['Player'])
        not_found_indices.append(i)

Index =  91 Not Found :  dimitris giannoulis
Index =  115 Not Found :  faik sakar
Index =  139 Not Found :  giorgos masouras
Index =  147 Not Found :  hennes behrens
Index =  169 Not Found :  jan niklas beste
Index =  182 Not Found :  jonah kusi asare
Index =  226 Not Found :  kjell arik watjen
Index =  310 Not Found :  mohammed amoura
Index =  337 Not Found :  noah pesch
Index =  355 Not Found :  paul hennrich
Index =  434 Not Found :  wooyeong jeong
Index =  442 Not Found :  alex grimaldo

In [16]:
for idx, name in zip(not_found_indices, name_not_found):
    last_name_1 = name.split(' ')[-1]
    found = False
    for j in range(len(data_value)):
        last_name_2 = data_value.iloc[j]['Name'].split(' ')[-1]
        if last_name_1 == last_name_2:
            merged = pd.concat([
                data_info.iloc[idx],
                data_value.iloc[j].drop('Name')  # bỏ cột trùng
            ])
            merged_rows.append(merged)
            found = True
            break
    if not found:
        print('Still not found:', name)

Still not found: faik sakar
Still not found: jonah kusi asare
Still not found: noah pesch
Still not found: paul hennrich

In [17]:
for i in range(len(merged_rows)):
    merged_rows[i] = merged_rows[i].to_dict()

In [18]:
data = pd.DataFrame(merged_rows)

In [19]:
data['Player'] = data['Player'].str.title()

In [20]:
data.to_csv('Final_Bundesliga.csv')