In [172]:
import pandas as pd
import numpy as np

In [173]:
data_summary = pd.read_csv('data_summary_EPL.csv')
base_info_EPL = pd.read_csv('base_info_EPL.csv')

In [174]:
data_summary

,Player,Apps,Mins,Goals,Assists,Yel,Red,SpG,PS%,AerialsWon,MotM,Rating
0,Mohamed Salah,32,2840,27,18,1,-,3.4,74.3,0.3,10,7.75
1,Bukayo Saka,16(3),1372,6,10,3,-,2.7,84.3,0.4,6,7.59
2,Alexander Isak,29,2351,21,6,1,-,2.9,75.2,0.9,5,7.44
3,Matheus Cunha,24(3),2168,14,4,3,-,3.3,77.9,0.4,8,7.37
4,Erling Haaland,28,2484,21,3,2,-,3.6,66.4,1.8,6,7.37
...,...,...,...,...,...,...,...,...,...,...,...,...
559,Mason Holgate,0(1),5,-,-,-,-,-,-,-,-,5.87
560,Harry Clarke,4(3),378,-,-,1,1,0.1,82.2,1.4,-,5.85
561,Jayden Danns,0(1),10,-,-,-,-,-,100,-,-,5.84
562,Ben Godfrey,2,110,-,-,1,-,-,83.3,1,-,5.54
563,Altay Bayindir,1,90,-,-,-,-,-,49.1,1,-,4.94

In [175]:
base_info_EPL['Club'].value_counts()

Club
Leicester               30
Ipswich                 30
West Ham                29
Tottenham               29
Manchester City         28
Southampton             28
Chelsea                 27
Fulham                  27
Brighton                26
Wolves                  26
Manchester United       26
Bournemouth             25
Aston Villa             25
Everton                 25
Arsenal                 24
Liverpool               24
Brentford               24
Crystal Palace          23
Nottingham Forest       22
Newcastle               22
West Bromwich Albion     3
Napoli                   3
Sheffield United         3
Derby                    2
AC Milan                 2
Middlesbrough            2
Juventus                 2
Aberdeen                 1
Bayer Leverkusen         1
Al Shabab                1
Celtic                   1
Strasbourg               1
Queens Park Rangers      1
PSV Eindhoven            1
Preston                  1
Birmingham               1
Cardiff                  1
Stoke                    1
Gillingham               1
Valencia                 1
Burnley                  1
Atlanta United           1
Feyenoord                1
Exeter                   1
Genoa                    1
Mallorca                 1
RB Leipzig               1
Fenerbahce               1
Anderlecht               1
Real Betis               1
Wolfsburg                1
Al Nassr FC              1
Galatasaray              1
Augsburg                 1
Name: count, dtype: int64

In [176]:
name_counts = base_info_EPL['Name'].value_counts()
duplicate_name = name_counts[name_counts > 1].index
duplicate_name

Index(['Joachim Andersen', 'Odsonne Édouard', 'Marcus Rashford',
       'Evan Ferguson', 'Jordan Ayew', 'James Ward-Prowse', 'Jaden Philogene',
       'Reiss Nelson', 'Julio Enciso', 'Trevoh Chalobah', 'Carlos Alcaraz',
       'Axel Disasi'],
      dtype='object', name='Name')

In [177]:
for name in duplicate_name:
    print(base_info_EPL[base_info_EPL['Name'] == name])

                 Name    Club                        Age Height National  \
113  Joachim Andersen  Fulham  28 years old (31-05-1996)  192cm  Denmark
436  Joachim Andersen  Fulham  28 years old (31-05-1996)  192cm  Denmark

             Positions
113  Defender (Centre)
436  Defender (Centre)
                Name       Club                        Age Height National  \
516  Odsonne Édouard  Leicester  27 years old (16-01-1998)  187cm   France
551  Odsonne Édouard  Leicester  27 years old (16-01-1998)  187cm   France

                                Positions
516  Attacking Midfielder (Left), Forward
551  Attacking Midfielder (Left), Forward
                Name         Club                        Age Height National  \
94   Marcus Rashford  Aston Villa  27 years old (31-10-1997)  180cm  England
159  Marcus Rashford  Aston Villa  27 years old (31-10-1997)  180cm  England

                                             Positions
94   Attacking Midfielder (Centre, Left, Right), Fo...
159  Attacking Midfielder (Centre, Left, Right), Fo...
              Name      Club                        Age Height National  \
456  Evan Ferguson  West Ham  20 years old (19-10-2004)  183cm  Ireland
473  Evan Ferguson  West Ham  20 years old (19-10-2004)  183cm  Ireland

    Positions
456   Forward
473   Forward
            Name       Club                        Age Height National  \
308  Jordan Ayew  Leicester  33 years old (11-09-1991)  182cm    Ghana
557  Jordan Ayew  Leicester  33 years old (11-09-1991)  182cm    Ghana

                                             Positions
308  Attacking Midfielder (Centre, Left, Right), Fo...
557  Attacking Midfielder (Centre, Left, Right), Fo...
                  Name      Club                        Age Height National  \
186  James Ward-Prowse  West Ham  30 years old (01-11-1994)  173cm  England
480  James Ward-Prowse  West Ham  30 years old (01-11-1994)  173cm  England

                      Positions
186  Midfielder (Centre, Right)
480  Midfielder (Centre, Right)
                Name     Club                        Age Height National  \
293  Jaden Philogene  Ipswich  23 years old (08-02-2002)  181cm  England
556  Jaden Philogene  Ipswich  23 years old (08-02-2002)  181cm  England

                    Positions
293  Midfielder (Left, Right)
556  Midfielder (Left, Right)
             Name    Club                        Age Height National  \
217  Reiss Nelson  Fulham  25 years old (10-12-1999)  175cm  England
476  Reiss Nelson  Fulham  25 years old (10-12-1999)  175cm  England

                    Positions
217  Midfielder (Left, Right)
476  Midfielder (Left, Right)
             Name     Club                        Age Height  National  \
53   Julio Enciso  Ipswich  21 years old (23-01-2004)  173cm  Paraguay
353  Julio Enciso  Ipswich  21 years old (23-01-2004)  173cm  Paraguay

                               Positions
53   Attacking Midfielder (Centre, Left)
353  Attacking Midfielder (Centre, Left)
                Name     Club                        Age Height National  \
68   Trevoh Chalobah  Chelsea  25 years old (05-07-1999)  190cm  England
254  Trevoh Chalobah  Chelsea  25 years old (05-07-1999)  190cm  England

                                             Positions
68   Defender (Centre, Right), Defensive Midfielder...
254  Defender (Centre, Right), Defensive Midfielder...
               Name     Club                        Age Height National  \
149  Carlos Alcaraz  Everton  22 years old (30-11-2002)  176cm      NaN
262  Carlos Alcaraz  Everton  22 years old (30-11-2002)  176cm      NaN

                              Positions
149  Midfielder (Centre, Left), Forward
262  Midfielder (Centre, Left), Forward
            Name         Club                        Age Height National  \
177  Axel Disasi  Aston Villa  27 years old (11-03-1998)  190cm   France
311  Axel Disasi  Aston Villa  27 years old (11-03-1998)  190cm   France

                    Positions
177  Defender (Centre, Right)
311  Defender (Centre, Right)

In [178]:
base_info_EPL.head(120)

,Name,Club,Age,Height,National,Positions
0,Mohamed Salah,Liverpool,32 years old (15-06-1992),175cm,Egypt,"Attacking Midfielder (Centre, Left, Right), Fo..."
1,Bukayo Saka,Arsenal,23 years old (05-09-2001),178cm,England,"Defender (Left), Midfielder (Centre, Left, Right)"
2,Alexander Isak,Newcastle,25 years old (21-09-1999),192cm,Sweden,"Attacking Midfielder (Left), Forward"
3,Matheus Cunha,Wolves,25 years old (27-05-1999),183cm,Brazil,"Attacking Midfielder (Centre, Left), Forward"
4,Erling Haaland,Manchester City,24 years old (21-07-2000),194cm,Norway,Forward
...,...,...,...,...,...,...
115,Milos Kerkez,Bournemouth,21 years old (07-11-2003),180cm,Hungary,"Defender (Left), Midfielder (Left)"
116,Jarrad Branthwaite,Everton,22 years old (27-06-2002),195cm,England,Defender (Centre)
117,Nico O'Reilly,Manchester City,20 years old (21-03-2005),188cm,England,Defender (Left)
118,Tyrone Mings,Aston Villa,32 years old (13-03-1993),196cm,England,"Defender (Centre, Left)"
119,Marshall Munetsi,Wolves,28 years old (22-06-1996),188cm,Zimbabwe,"Defender (Centre), Midfielder (Centre)"

In [179]:
data_summary.head(120)

,Player,Apps,Mins,Goals,Assists,Yel,Red,SpG,PS%,AerialsWon,MotM,Rating
0,Mohamed Salah,32,2840,27,18,1,-,3.4,74.3,0.3,10,7.75
1,Bukayo Saka,16(3),1372,6,10,3,-,2.7,84.3,0.4,6,7.59
2,Alexander Isak,29,2351,21,6,1,-,2.9,75.2,0.9,5,7.44
3,Matheus Cunha,24(3),2168,14,4,3,-,3.3,77.9,0.4,8,7.37
4,Erling Haaland,28,2484,21,3,2,-,3.6,66.4,1.8,6,7.37
...,...,...,...,...,...,...,...,...,...,...,...,...
115,Milos Kerkez,32,2810,2,5,4,-,0.5,80.1,0.7,1,6.81
116,Jarrad Branthwaite,23(2),2076,-,1,4,-,0.3,81.6,1.8,-,6.81
117,Nico O'Reilly,3(2),275,1,-,-,-,0.8,87.8,0.4,-,6.80
118,Tyrone Mings,10(2),961,-,-,1,-,0.7,89.1,2,-,6.80
119,Marshall Munetsi,7(1),610,1,1,-,-,1.9,74.8,2,-,6.80

Đổi tên thuộc tính

In [ ]:
file_csv = [
    'base_info_EPL.csv',
    'data_details_Aerial_EPL.csv',
    'data_details_Assists_EPL.csv',
    'data_details_Blocks_EPL.csv',
    'data_details_Cards_EPL.csv',
    'data_details_Clearances_EPL.csv',
    'data_details_Dribbles_EPL.csv',
    'data_details_Fouls_EPL.csv',
    'data_details_Goals_EPL.csv',
    'data_details_Interception_EPL.csv',
    'data_details_Key passes_EPL.csv',
    'data_details_Offsides_EPL.csv',
    'data_details_Passes_EPL.csv',
    'data_details_Possession loss_EPL.csv',
    'data_details_Saves_EPL.csv',
    'data_details_Shots_EPL.csv',
    'data_details_Tackles_EPL.csv',
    'data_summary_EPL.csv'
]
data_list = []
for file in file_csv:
    # Lấy tên đặc trưng của từng file : Aerial, Assists, Blocks, Cards, ...
    feature = file.split('_')[2]
    data_temp = pd.read_csv(file)
    if file in [ 'base_info_EPL.csv', 'data_summary_EPL.csv']:
        data_list.append(data_temp)
        continue

    new_columns = {}
    for col in data_temp.columns:
        new_columns[col] = f"{col}_{feature}"
    data_temp.rename(columns= new_columns, inplace= True)

    data_list.append(data_temp)


data = pd.concat(data_list, axis = 1)

data_details_Aerial_EPL.csv
data_details_Assists_EPL.csv
data_details_Blocks_EPL.csv
data_details_Cards_EPL.csv
data_details_Clearances_EPL.csv
data_details_Dribbles_EPL.csv
data_details_Fouls_EPL.csv
data_details_Goals_EPL.csv
data_details_Interception_EPL.csv
data_details_Key passes_EPL.csv
data_details_Offsides_EPL.csv
data_details_Passes_EPL.csv
data_details_Possession loss_EPL.csv
data_details_Saves_EPL.csv
data_details_Shots_EPL.csv
data_details_Tackles_EPL.csv

In [181]:
data.columns

Index(['Name', 'Club', 'Age', 'Height', 'National', 'Positions',
       'Total_Aerial', 'Won_Aerial', 'Lost_Aerial', 'Cross_Assists',
       'Corner_Assists', 'Throughball_Assists', 'Freekick_Assists',
       'Throwin_Assists', 'Other_Assists', 'Total_Assists',
       'ShotsBlocked_Blocks', 'CrossesBlocked_Blocks', 'PassesBlocked_Blocks',
       'Yellow_Cards', 'Red_Cards', 'Total_Clearances',
       'Unsuccessful_Dribbles', 'Successful_Dribbles',
       'Total Dribbles_Dribbles', 'Fouled_Fouls', 'Fouls_Fouls', 'Total_Goals',
       'SixYardBox_Goals', 'PenaltyArea_Goals', 'OutOfBox_Goals',
       'Total_Interception', 'Total_Key passes', 'Long_Key passes',
       'Short_Key passes', 'CaughtOffside_Offsides', 'Total_Passes',
       'AccLB_Passes', 'InAccLB_Passes', 'AccSP_Passes', 'InAccSP_Passes',
       'UnsuccessfulTouches_Possession loss', 'Dispossessed_Possession loss',
       'Total_Saves', 'SixYardBox_Saves', 'PenaltyArea_Saves',
       'OutOfBox_Saves', 'Total_Shots', 'OutOfBox_Shots', 'SixYardBox_Shots',
       'PenaltyArea_Shots', 'TotalTackles_Tackles', 'DribbledPast_Tackles',
       'TotalAttemptedTackles_Tackles', 'Player', 'Apps', 'Mins', 'Goals',
       'Assists', 'Yel', 'Red', 'SpG', 'PS%', 'AerialsWon', 'MotM', 'Rating'],
      dtype='object')

In [186]:
for col in data.columns:
    num_null = data[col].isna().sum()
    print(col, num_null)

Name 0
Club 0
Age 1
Height 3
National 30
Positions 0
Total_Aerial 0
Won_Aerial 0
Lost_Aerial 0
Cross_Assists 0
Corner_Assists 0
Throughball_Assists 0
Freekick_Assists 0
Throwin_Assists 0
Other_Assists 0
Total_Assists 0
ShotsBlocked_Blocks 0
CrossesBlocked_Blocks 0
PassesBlocked_Blocks 0
Yellow_Cards 0
Red_Cards 0
Total_Clearances 0
Unsuccessful_Dribbles 0
Successful_Dribbles 0
Total Dribbles_Dribbles 0
Fouled_Fouls 0
Fouls_Fouls 0
Total_Goals 0
SixYardBox_Goals 0
PenaltyArea_Goals 0
OutOfBox_Goals 0
Total_Interception 0
Total_Key passes 0
Long_Key passes 0
Short_Key passes 0
CaughtOffside_Offsides 0
Total_Passes 0
AccLB_Passes 0
InAccLB_Passes 0
AccSP_Passes 0
InAccSP_Passes 0
UnsuccessfulTouches_Possession loss 0
Dispossessed_Possession loss 0
Total_Saves 0
SixYardBox_Saves 0
PenaltyArea_Saves 0
OutOfBox_Saves 0
Total_Shots 0
OutOfBox_Shots 0
SixYardBox_Shots 0
PenaltyArea_Shots 0
TotalTackles_Tackles 0
DribbledPast_Tackles 0
TotalAttemptedTackles_Tackles 0
Player 0
Apps 0
Mins 0
Goals 0
Assists 0
Yel 0
Red 0
SpG 0
PS% 0
AerialsWon 0
MotM 0
Rating 0

Vấn đề missing value sẽ được giải quyết sau. Bước hiện tại chỉ xử lý các vấn đề :
- Trùng lặp các cầu thủ (một mùa giải cầu thủ có thể mang cho mượn ở các clb khác nhau)
- Một số đội bóng đã xuống hạng nhưng vẫn được thêm vào (dữ liệu có sai sót)

In [188]:
count_club  = data['Club'].value_counts()
count_club

Club
Leicester               30
Ipswich                 30
West Ham                29
Tottenham               29
Manchester City         28
Southampton             28
Chelsea                 27
Fulham                  27
Brighton                26
Wolves                  26
Manchester United       26
Bournemouth             25
Aston Villa             25
Everton                 25
Arsenal                 24
Liverpool               24
Brentford               24
Crystal Palace          23
Nottingham Forest       22
Newcastle               22
West Bromwich Albion     3
Napoli                   3
Sheffield United         3
Derby                    2
AC Milan                 2
Middlesbrough            2
Juventus                 2
Aberdeen                 1
Bayer Leverkusen         1
Al Shabab                1
Celtic                   1
Strasbourg               1
Queens Park Rangers      1
PSV Eindhoven            1
Preston                  1
Birmingham               1
Cardiff                  1
Stoke                    1
Gillingham               1
Valencia                 1
Burnley                  1
Atlanta United           1
Feyenoord                1
Exeter                   1
Genoa                    1
Mallorca                 1
RB Leipzig               1
Fenerbahce               1
Anderlecht               1
Real Betis               1
Wolfsburg                1
Al Nassr FC              1
Galatasaray              1
Augsburg                 1
Name: count, dtype: int64

In [190]:
valid_club = count_club[count_club > 20].index
data = data[data['Club'].isin(valid_club)]

In [191]:
data['Club'].value_counts()

Club
Leicester            30
Ipswich              30
Tottenham            29
West Ham             29
Southampton          28
Manchester City      28
Fulham               27
Chelsea              27
Manchester United    26
Wolves               26
Brighton             26
Bournemouth          25
Aston Villa          25
Everton              25
Brentford            24
Arsenal              24
Liverpool            24
Crystal Palace       23
Nottingham Forest    22
Newcastle            22
Name: count, dtype: int64

In [193]:
count_name = data['Name'].value_counts()
invalid_name = count_name[count_name > 1].index
invalid_name

Index(['Julio Enciso', 'Jaden Philogene', 'Axel Disasi', 'Carlos Alcaraz',
       'Jordan Ayew', 'Reiss Nelson', 'James Ward-Prowse', 'Odsonne Édouard',
       'Joachim Andersen', 'Evan Ferguson', 'Marcus Rashford',
       'Trevoh Chalobah'],
      dtype='object', name='Name')

In [195]:
for name in invalid_name:
    print(data[data['Name'] == name])

             Name     Club                        Age Height  National  \
53   Julio Enciso  Ipswich  21 years old (23-01-2004)  173cm  Paraguay
353  Julio Enciso  Ipswich  21 years old (23-01-2004)  173cm  Paraguay

                               Positions Total_Aerial Won_Aerial Lost_Aerial  \
53   Attacking Midfielder (Centre, Left)          2.4        0.6         1.8
353  Attacking Midfielder (Centre, Left)          0.9        0.5         0.4

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM  \
53            0.1  ...  510     1       3   3   -  2.3  72.9        0.6    -
353             -  ...  288     -       -   -   -  1.7  73.8        0.5    -

    Rating
53    6.96
353   6.37

[2 rows x 66 columns]
                Name     Club                        Age Height National  \
293  Jaden Philogene  Ipswich  23 years old (08-02-2002)  181cm  England
556  Jaden Philogene  Ipswich  23 years old (08-02-2002)  181cm  England

                    Positions Total_Aerial Won_Aerial Lost_Aerial  \
293  Midfielder (Left, Right)          0.8        0.5         0.3
556  Midfielder (Left, Right)          0.5          -         0.5

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM  \
293             -  ...  475     2       -   1   -  1.2  78.4        0.5    1
556             -  ...  326     -       -   2   1  0.6  76.5          -    -

    Rating
293   6.47
556   5.92

[2 rows x 66 columns]
            Name         Club                        Age Height National  \
177  Axel Disasi  Aston Villa  27 years old (11-03-1998)  190cm   France
311  Axel Disasi  Aston Villa  27 years old (11-03-1998)  190cm   France

                    Positions Total_Aerial Won_Aerial Lost_Aerial  \
177  Defender (Centre, Right)          2.3        1.3           1
311  Defender (Centre, Right)          1.2        0.8         0.3

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM  \
177             -  ...  459     -       -   2   -  0.3  89.3        1.3    -
311             -  ...  365     1       -   1   -  0.3  91.7        0.8    -

    Rating
177   6.69
311   6.44

[2 rows x 66 columns]
               Name     Club                        Age Height National  \
149  Carlos Alcaraz  Everton  22 years old (30-11-2002)  176cm      NaN
262  Carlos Alcaraz  Everton  22 years old (30-11-2002)  176cm      NaN

                              Positions Total_Aerial Won_Aerial Lost_Aerial  \
149  Midfielder (Centre, Left), Forward          1.7          1         0.7
262  Midfielder (Centre, Left), Forward            1          1           -

    Cross_Assists  ... Mins Goals Assists Yel Red SpG   PS% AerialsWon MotM  \
149             -  ...  432     1       1   3   -   2  79.2          1    -
262             -  ...    9     -       -   -   -   1   100          1    -

    Rating
149   6.74
262   6.52

[2 rows x 66 columns]
            Name       Club                        Age Height National  \
308  Jordan Ayew  Leicester  33 years old (11-09-1991)  182cm    Ghana
557  Jordan Ayew  Leicester  33 years old (11-09-1991)  182cm    Ghana

                                             Positions Total_Aerial  \
308  Attacking Midfielder (Centre, Left, Right), Fo...          3.6
557  Attacking Midfielder (Centre, Left, Right), Fo...            2

    Won_Aerial Lost_Aerial Cross_Assists  ...  Mins Goals Assists Yel Red SpG  \
308        1.4         2.2             -  ...  1314     4       -   5   -   1
557          1           1             -  ...    20     -       -   1   -   1

      PS% AerialsWon MotM Rating
308  77.9        1.4    -   6.44
557  88.9          1    -   5.90

[2 rows x 66 columns]
             Name    Club                        Age Height National  \
217  Reiss Nelson  Fulham  25 years old (10-12-1999)  175cm  England
476  Reiss Nelson  Fulham  25 years old (10-12-1999)  175cm  England

                    Positions Total_Aerial Won_Aerial Lost_Aerial  \
217  Midfielder (Left, Right)          0.4          -         0.4
476  Midfielder (Left, Right)            -          -           -

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM  \
217             -  ...  486     1       1   1   -  1.1  91.4          -    -
476             -  ...    2     -       -   -   -    -     -          -    -

    Rating
217   6.60
476   6.15

[2 rows x 66 columns]
                  Name      Club                        Age Height National  \
186  James Ward-Prowse  West Ham  30 years old (01-11-1994)  173cm  England
480  James Ward-Prowse  West Ham  30 years old (01-11-1994)  173cm  England

                      Positions Total_Aerial Won_Aerial Lost_Aerial  \
186  Midfielder (Centre, Right)          0.8        0.6         0.2
480  Midfielder (Centre, Right)          0.9        0.3         0.6

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM  \
186           0.1  ...  672     -       1   2   -  0.4  91.6        0.6    -
480             -  ...  399     -       1   -   1  0.2  86.4        0.3    -

    Rating
186   6.66
480   6.14

[2 rows x 66 columns]
                Name       Club                        Age Height National  \
516  Odsonne Édouard  Leicester  27 years old (16-01-1998)  187cm   France
551  Odsonne Édouard  Leicester  27 years old (16-01-1998)  187cm   France

                                Positions Total_Aerial Won_Aerial Lost_Aerial  \
516  Attacking Midfielder (Left), Forward          0.5        0.3         0.3
551  Attacking Midfielder (Left), Forward          2.5        0.5           2

    Cross_Assists  ... Mins Goals Assists Yel Red  SpG PS% AerialsWon MotM  \
516             -  ...   26     -       -   -   -    -  75        0.3    -
551             -  ...  116     -       -   -   -  2.5  63        0.5    -

    Rating
516   6.05
551   5.95

[2 rows x 66 columns]
                 Name    Club                        Age Height National  \
113  Joachim Andersen  Fulham  28 years old (31-05-1996)  192cm  Denmark
436  Joachim Andersen  Fulham  28 years old (31-05-1996)  192cm  Denmark

             Positions Total_Aerial Won_Aerial Lost_Aerial Cross_Assists  ...  \
113  Defender (Centre)          3.9        2.4         1.5             -  ...
436  Defender (Centre)            2          2           -             -  ...

     Mins Goals Assists Yel Red  SpG   PS% AerialsWon MotM Rating
113  2033     -       -   5   1  0.6  83.2        2.4    1   6.81
436    90     -       -   1   -    1  74.4          2    -   6.25

[2 rows x 66 columns]
              Name      Club                        Age Height National  \
456  Evan Ferguson  West Ham  20 years old (19-10-2004)  183cm  Ireland
473  Evan Ferguson  West Ham  20 years old (19-10-2004)  183cm  Ireland

    Positions Total_Aerial Won_Aerial Lost_Aerial Cross_Assists  ... Mins  \
456   Forward            2        0.8         1.2             -  ...  138
473   Forward            1        0.3         0.7             -  ...  236

    Goals Assists Yel Red  SpG   PS% AerialsWon MotM Rating
456     -       -   -   -  0.8  78.1        0.8    -   6.20
473     1       -   -   -  0.5  75.4        0.3    -   6.16

[2 rows x 66 columns]
                Name         Club                        Age Height National  \
94   Marcus Rashford  Aston Villa  27 years old (31-10-1997)  180cm  England
159  Marcus Rashford  Aston Villa  27 years old (31-10-1997)  180cm  England

                                             Positions Total_Aerial  \
94   Attacking Midfielder (Centre, Left, Right), Fo...            1
159  Attacking Midfielder (Centre, Left, Right), Fo...          0.8

    Won_Aerial Lost_Aerial Cross_Assists  ... Mins Goals Assists Yel Red  SpG  \
94         0.1         0.9           0.1  ...  360     1       2   -   -  1.9
159        0.3         0.5           0.1  ...  983     4       1   2   -  1.1

      PS% AerialsWon MotM Rating
94   82.8        0.1    1   6.85
159  76.9        0.3    -   6.72

[2 rows x 66 columns]
                Name     Club                        Age Height National  \
68   Trevoh Chalobah  Chelsea  25 years old (05-07-1999)  190cm  England
254  Trevoh Chalobah  Chelsea  25 years old (05-07-1999)  190cm  England

                                             Positions Total_Aerial  \
68   Defender (Centre, Right), Defensive Midfielder...          3.4
254  Defender (Centre, Right), Defensive Midfielder...            3

    Won_Aerial Lost_Aerial Cross_Assists  ...  Mins Goals Assists Yel Red  \
68         1.8         1.6             -  ...  1063     3       -   1   -
254          2           1             -  ...   566     -       1   1   -

     SpG   PS% AerialsWon MotM Rating
68   0.9  79.8        1.8    -   6.92
254  0.7  90.2          2    1   6.53

[2 rows x 66 columns]